/* ============================================================
   لینک درس‌ها — دانشگاه آزاد بندرعباس
   فایل اختصاصی داده‌ها
   ------------------------------------------------------------
   ساختار هر پست:
   {
     title:     عنوان درس / گروه
     subtitle:  استاد، روز، ساعت یا توضیح
     platform:  rubika | bale | telegram | whatsapp | eitaa | soroush | igap | other
     url:       لینک کامل
     category:  دسته‌بندی برای فیلتر
     tags:      آرایه برچسب
   }
   ============================================================ */

const POSTS = [

/* ═══════════════════════════════════════════════════════════
   📚 دروس عمومی و معارف
   ═══════════════════════════════════════════════════════════ */

/* --- تفسیر موضوعی قرآن --- */
{title:'تفسیر موضوعی قرآن', subtitle:'استاد شورانگیز خادمی — خواهران', platform:'bale', url:'https://ble.ir/join/BdGSXs5UwM', category:'عمومی', tags:['تفسیر قرآن']},
{title:'تفسیر موضوعی قرآن', subtitle:'استاد کرتی (خواهران) — ترم تابستان', platform:'bale', url:'https://ble.ir/876089z', category:'عمومی', tags:['تفسیر قرآن','تابستان']},
{title:'تفسیر موضوعی قرآن کریم', subtitle:'استاد باوقار زعیمی — خواهران، تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBEHIHFDJ0MKSBIZXXJHGFHTAXYHSBXD', category:'عمومی', tags:['تفسیر قرآن']},
{title:'تفسیر موضوعی قرآن', subtitle:'استاد غلامرضا عارفیان — دوشنبه ۸ تا ۱۱ و ۱۴ تا ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BBDBCCIGH0MCLFCBFVPDPOYABUZKMPUC', category:'عمومی', tags:['تفسیر قرآن']},
{title:'تفسیر موضوعی قرآن', subtitle:'استاد امینی — یکشنبه ۱۱ تا ۱۴', platform:'bale', url:'https://ble.ir/join/Dy5N9qgMoG', category:'عمومی', tags:['تفسیر قرآن']},

/* --- انس با قرآن --- */
{title:'انس با قرآن', subtitle:'استاد باقری دهبارز', platform:'bale', url:'https://ble.ir/join/6nd1rJctu9', category:'عمومی', tags:['انس با قرآن']},
{title:'انس با قرآن', subtitle:'استاد محمد کمالی باغستانی — برادران', platform:'bale', url:'https://ble.ir/join/8i9sLRFJ27', category:'عمومی', tags:['انس با قرآن']},
{title:'انس با قرآن', subtitle:'استاد مهتاب محمودیان — سه‌شنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBHCFCGBG0QQYLWYNDEBJSAGOLUWZBNN', category:'عمومی', tags:['انس با قرآن']},
{title:'انس با قرآن', subtitle:'استاد مهتاب کرامتیان — سه‌شنبه ۱۸ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BBHCJDGIA0SHHKQDHFPIETSEFHIRPCCP', category:'عمومی', tags:['انس با قرآن']},
{title:'انس با قرآن', subtitle:'استاد مهتاب محمودیان — دوشنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBGHGGDGH0MITEGBZLNBILTIUFDNUXHL', category:'عمومی', tags:['انس با قرآن']},
{title:'انس با قرآن', subtitle:'استاد لیلا تیزرو — تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBGJAECBC0YRKUKUHSJUJULXRYVHVEXT', category:'عمومی', tags:['انس با قرآن']},
{title:'انس با قرآن', subtitle:'استاد کمالی — برادران', platform:'bale', url:'https://ble.ir/join/8nke9NGMsd', category:'عمومی', tags:['انس با قرآن']},

/* --- اندیشه اسلامی ۱ و ۲ --- */
{title:'اندیشه اسلامی ۱ و ۲', subtitle:'استاد عامری', platform:'rubika', url:'https://rubika.ir/joing/BADJEEADB0JRIRWVFHXTLOBGQFZWWNGC', category:'عمومی', tags:['اندیشه ۱','اندیشه ۲']},
{title:'اندیشه اسلامی ۱ (مبدأ و معاد)', subtitle:'استاد اشرف باقری‌پور — تمام ساعات', platform:'bale', url:'https://ble.ir/join/HvQ9nbMTRb', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱ (مبدأ و معاد)', subtitle:'استاد اشرف باقری‌پور — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BAAGGICDB0VGALBZGATWGQYCYAXFZTHI', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱', subtitle:'استاد اشرف باقری‌پور — یکشنبه ۸ تا ۱۰', platform:'rubika', url:'https://rubika.ir/joing/BACJDGGGC0ACUQXRQNAYRVWREHOFENPF', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱', subtitle:'استاد اشرف باقری‌پور — یکشنبه ۱۰ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BADDBAAGH0PYRRFMAKQPUUPFJMYYRQEL', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱', subtitle:'استاد اشرف باقری‌پور — یکشنبه ۱۲ تا ۱۴', platform:'bale', url:'https://ble.ir/join/Ev56cMWygE', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱', subtitle:'استاد اشرف باقری‌پور — ساعت ۱۴ تا ۱۶', platform:'rubika', url:'https://rubika.ir/joing/BBHBDIBHD0FUFLEJDKJQBVVFGIYHATLK', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱', subtitle:'استاد رویا بناکار — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHHEHEE0MHVTTPRKYUIOMOLATHEOQB', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱', subtitle:'استاد رویا بناکار — تمام ساعات (ایتا)', platform:'eitaa', url:'https://eitaa.com/joinchat/1561921237C45ae11078c', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱', subtitle:'استاد رویا بناکار — چهارشنبه ۱۲ تا ۱۴', platform:'bale', url:'https://ble.ir/join/23MwPKcehe', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱', subtitle:'استاد صفدری نیاک', platform:'rubika', url:'https://rubika.ir/joing/BBGDEAIJD0AWDQKDWTPYVIVDIRUJNVPQ', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۱', subtitle:'استاد بناکار', platform:'rubika', url:'https://rubika.ir/joing/BBGICFDAI0PDUPOUFUGFFACXKHIELJLU', category:'عمومی', tags:['اندیشه ۱']},
{title:'اندیشه اسلامی ۲', subtitle:'استاد رویا بناکار — تمام ساعات (ایتا)', platform:'eitaa', url:'https://eitaa.com/joinchat/304547541Cc89fb28c4b', category:'عمومی', tags:['اندیشه ۲']},
{title:'اندیشه اسلامی ۲', subtitle:'استاد سامانی — دوشنبه ۸ تا ۱۰', platform:'eitaa', url:'https://eitaa.com/joinchat/1781139207Cd5fa539ba9', category:'عمومی', tags:['اندیشه ۲']},
{title:'اندیشه اسلامی ۲', subtitle:'استاد مصطفی سامانی', platform:'rubika', url:'https://rubika.ir/joing/BBGHAJGJA0LVIKKSTWENXHYJANKXEAWQ', category:'عمومی', tags:['اندیشه ۲']},
{title:'اندیشه اسلامی ۲ (نبوت و امامت)', subtitle:'استاد مصطفی سامانی — دوشنبه ۱۲ تا ۱۴', platform:'eitaa', url:'https://eitaa.com/joinchat/933103366C53b1647a1e', category:'عمومی', tags:['اندیشه ۲']},
{title:'اندیشه اسلامی ۲', subtitle:'استاد رویا بناکار — ترم تابستان', platform:'eitaa', url:'https://eitaa.com/joinchat/1285293756C52cb52645b', category:'عمومی', tags:['اندیشه ۲','تابستان']},
{title:'اندیشه اسلامی ۲', subtitle:'استاد مصطفی عامری سیاهویی — خواهران، تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBCIGCFDG0YPZIXVZLCPLSKXNRPJIHTP', category:'عمومی', tags:['اندیشه ۲','تابستان']},
{title:'اندیشه اسلامی ۱ و ۲', subtitle:'استاد عامری سیاهویی — خواهران و برادران', platform:'rubika', url:'https://rubika.ir/joing/BBDCDAAEH0ONSFVQJPHIAGKBWOBZGFLW', category:'عمومی', tags:['اندیشه ۱','اندیشه ۲']},
{title:'اندیشه اسلامی ۱ و ۲', subtitle:'استاد عامری', platform:'rubika', url:'https://rubika.ir/joing/BBDCDAAEH0IULWPEZWERQTXFEVCCNQUI', category:'عمومی', tags:['اندیشه ۱','اندیشه ۲']},

/* --- اندیشه‌های امامین و وصایا --- */
{title:'اندیشه‌های امامین انقلاب و وصایا', subtitle:'استاد محمد کمالی باغستانی — ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBDAIIFHH0KEDKARJHXXDBSLLQQGINNY', category:'عمومی', tags:['اندیشه و وصایا','تابستان']},
{title:'اندیشه‌های امامین و وصایا', subtitle:'استاد حمید باقری دهبارز — خواهران', platform:'rubika', url:'https://rubika.ir/joing/BAAEFCGED0ZAONROTPKWRQGIRGISABCR', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه‌های امامین و وصایا', subtitle:'استاد حمید باقری دهبارز — خواهران (ایتا)', platform:'eitaa', url:'https://eitaa.com/joinchat/4255581724C4908d232e8', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه و وصایای امام خمینی', subtitle:'استاد فاطمه برزن — خواهران', platform:'rubika', url:'https://rubika.ir/joing/BABBCEBGI0SAODAQDUOAGKLNVPGJOYLA', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه‌های امامین انقلاب اسلامی', subtitle:'استاد محمد کمالی باغستانی — سه‌شنبه ۱۸ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BADDAEBDH0AUZLAKWEFZAJHSYNGJGWKW', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه‌ها و وصایای امام خمینی', subtitle:'استاد داود سعیدی — شنبه ۲ تا ۴', platform:'rubika', url:'https://rubika.ir/joing/BABGCCDFD0KKQWFWUUPFMMTPNOJHGDZA', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه‌های امامین انقلاب اسلامی', subtitle:'استاد داوود سعیدی', platform:'rubika', url:'https://rubika.ir/joing/BABHIGBIA0CGXDUACBZQATOQAESTZHYZ', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'وصایا و انقلاب اسلامی', subtitle:'استاد داوود سعیدی', platform:'rubika', url:'https://rubika.ir/joing/BABIBEFIG0XSKILQWRYEYFEKNTQJETSC', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه‌های امامین و وصایا', subtitle:'استاد حمید باقری دهبارز — کامپیوتر', platform:'rubika', url:'https://rubika.ir/joing/BAAEHIDJA0OPBXNZCRKPFTPHYEBLFKPU', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه امامین و انقلاب اسلامی', subtitle:'استاد خوارزمی — ۱۲ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BAEEDHDEJ0HERIDAAOERCTZMHIQCUVBV', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه امامین و انقلاب اسلامی', subtitle:'استاد خوارزمی — ۱۲ تا ۱۴ (ایتا)', platform:'eitaa', url:'https://eitaa.com/joinchat/3455583772Cb25e4e2922', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه و وصایا', subtitle:'استاد کمالی باغستانی', platform:'rubika', url:'https://rubika.ir/joing/BBFJAEACH0VUHUIMPLXZGUWZIZYFVUQD', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه وصایا', subtitle:'استاد کمالی', platform:'whatsapp', url:'https://chat.whatsapp.com/Iv01MCc3Deg0Yi4jYCtgtw', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه وصایا', subtitle:'استاد کمالی — خواهران', platform:'whatsapp', url:'https://chat.whatsapp.com/K7JR8D1hWGUDKRopNkRwIj', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه‌های امامین انقلاب و وصایا', subtitle:'دکتر حمید باقری دهبارز — شنبه ۱۶ تا ۱۸', platform:'whatsapp', url:'https://chat.whatsapp.com/CiPDfwKPthB6TfckWksdgM', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'وصایای حضرت امام خمینی', subtitle:'استاد داود سعیدی', platform:'rubika', url:'https://rubika.ir/joing/BBDFJGGAH0KEHYSMFTXLAKVCCFWPABDS', category:'عمومی', tags:['اندیشه و وصایا']},
{title:'اندیشه امامین و انقلاب اسلامی', subtitle:'استاد خوارزمی — ۱۲ تا ۱۴ (روبیکا ۲)', platform:'rubika', url:'https://rubika.ir/joing/BAECIAEEC0YBJENNFJAJBJBDLZOWAYHW', category:'عمومی', tags:['اندیشه و وصایا']},

/* --- دانش خانواده --- */
{title:'دانش خانواده و جمعیت', subtitle:'استاد سمیه کرتی — تمام ساعات، ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBCIDGIID0EDDKRFDDUTBZRVOSZUBLBB', category:'عمومی', tags:['دانش خانواده','تابستان']},
{title:'دانش خانواده و جمعیت', subtitle:'استاد سمیه کرتی — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/7Aii2H4iGG', category:'عمومی', tags:['دانش خانواده']},
{title:'دانش خانواده و جمعیت', subtitle:'استاد سمیه کرتی — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHFCBIJ0CBFOZFBBCWQAXOISWQPBBV', category:'عمومی', tags:['دانش خانواده']},
{title:'دانش خانواده — پنجشنبه ۸ تا ۱۰', subtitle:'استاد سمیه کرتی', platform:'bale', url:'https://ble.ir/join/HLN3gJZGKD', category:'عمومی', tags:['دانش خانواده']},
{title:'دانش خانواده — پنجشنبه ۱۰ تا ۱۲', subtitle:'استاد سمیه کرتی', platform:'bale', url:'https://ble.ir/join/35SqpGVGtD', category:'عمومی', tags:['دانش خانواده']},
{title:'دانش خانواده — پنجشنبه ۱۲ تا ۱۴', subtitle:'استاد سمیه کرتی', platform:'bale', url:'https://ble.ir/join/7Q9Ti56kXv', category:'عمومی', tags:['دانش خانواده']},
{title:'دانش خانواده — پنجشنبه ۱۴ تا ۱۶', subtitle:'استاد سمیه کرتی', platform:'bale', url:'https://ble.ir/join/AqUrMo3sn4', category:'عمومی', tags:['دانش خانواده']},
{title:'دانش خانواده — جمعه ۸ تا ۱۰', subtitle:'استاد سمیه کرتی', platform:'bale', url:'https://ble.ir/join/5XQcxMLeAp', category:'عمومی', tags:['دانش خانواده']},
{title:'دانش خانواده — جمعه ۱۰ تا ۱۲', subtitle:'استاد سمیه کرتی', platform:'bale', url:'https://ble.ir/join/4jsbfTF3qQ', category:'عمومی', tags:['دانش خانواده']},
{title:'دانش خانواده — جمعه ۱۲ تا ۱۴', subtitle:'استاد سمیه کرتی', platform:'bale', url:'https://ble.ir/join/F8VvcDuYxF', category:'عمومی', tags:['دانش خانواده']},
{title:'دانش خانواده — جمعه ۱۴ تا ۱۶', subtitle:'استاد سمیه کرتی', platform:'bale', url:'https://ble.ir/join/5D5oR1bopP', category:'عمومی', tags:['دانش خانواده']},

/* --- تاریخ --- */
{title:'تاریخ تحلیلی صدر اسلام', subtitle:'استاد عارفیان — خواهران، تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBEHIHGIG0BZISQYYSKMCOIASYPDBXCK', category:'عمومی', tags:['تاریخ صدر اسلام']},
{title:'تاریخ تحلیلی صدر اسلام', subtitle:'استاد عارفیان — خواهران', platform:'rubika', url:'https://rubika.ir/joing/BBDBIGCFH0VKCDXVJYKHOBIRRWSLPDQT', category:'عمومی', tags:['تاریخ صدر اسلام']},
{title:'تاریخ تحلیلی صدر اسلام', subtitle:'استاد عارفیان — برادران، ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBDBJDABG0IEFNYKIFSYJNVBYNVFVMNC', category:'عمومی', tags:['تاریخ صدر اسلام','تابستان']},
{title:'تاریخ فرهنگ و تمدن اسلام و ایران', subtitle:'استاد تراهی — خواهران، تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBEHIHGBJ0AVIHHZIIIXHWHSWBDKFAIS', category:'عمومی', tags:['تاریخ و تمدن']},
{title:'تاریخ فرهنگ و تمدن اسلام و ایران', subtitle:'استاد امینی', platform:'rubika', url:'https://rubika.ir/joing/BBFJAEABB0FLPIOIYOQZFKWCPBVONKSN', category:'عمومی', tags:['تاریخ و تمدن']},
{title:'تاریخ فرهنگ و تمدن', subtitle:'استاد جلیل تراهی — خواهران، پنجشنبه ۱۰', platform:'eitaa', url:'https://eitaa.com/joinchat/2900559628C7df4f6e8b2', category:'عمومی', tags:['تاریخ و تمدن']},
{title:'تاریخ فرهنگ و تمدن', subtitle:'استاد عارفیان', platform:'rubika', url:'https://rubika.ir/joing/BBDFBCDHJ0NSVPKOEHYJVYCOONQIGLDA', category:'عمومی', tags:['تاریخ و تمدن']},

/* --- انقلاب اسلامی --- */
{title:'انقلاب اسلامی', subtitle:'استاد آران — سه‌شنبه ۲ تا ۴', platform:'rubika', url:'https://rubika.ir/joing/BAEEJJDBH0MMSISECPLMFHKJLWIZBVVD', category:'عمومی', tags:['انقلاب اسلامی']},
{title:'انقلاب اسلامی', subtitle:'استاد اصغر درویشی', platform:'rubika', url:'https://rubika.ir/ISLAMICREVOLUTIONdrDARVISHI', category:'عمومی', tags:['انقلاب اسلامی']},
{title:'انقلاب اسلامی', subtitle:'استاد آران — ویژه برادران', platform:'bale', url:'https://ble.ir/join/6XKxLYnLK8', category:'عمومی', tags:['انقلاب اسلامی']},
{title:'انقلاب اسلامی', subtitle:'استاد آران', platform:'rubika', url:'https://rubika.ir/joing/BBCIIICEB0YITIQDIMSRTOQJBROZHFFT', category:'عمومی', tags:['انقلاب اسلامی']},

/* --- ورزش و تربیت بدنی --- */
{title:'تربیت بدنی', subtitle:'استاد دادگر — ساعت ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BAIFEFJAH0ARLNOZNTFENBMGXPOMPLQB', category:'عمومی', tags:['ورزش']},
{title:'تربیت بدنی', subtitle:'استاد هانی اعتمادی — امتحان عملی چهارشنبه ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BAJICEIDB0MXOHGZKWKHTFNZKNXOFPUI', category:'عمومی', tags:['ورزش']},
{title:'ورزش ۱', subtitle:'استاد کمانی — شنبه ۱۰ تا ۱۲ و ۱۲ تا ۱۴', platform:'bale', url:'https://ble.ir/join/72yQfK2aHE', category:'عمومی', tags:['ورزش']},
{title:'ورزش', subtitle:'استاد فرخنده', platform:'rubika', url:'https://rubika.ir/joing/BAIDHIJHH0NNPBVQXPAUBETJJWEHWMLI', category:'عمومی', tags:['ورزش']},
{title:'ورزش‌های آبی', subtitle:'استاد اسیه نوائی — سه‌شنبه ۱۲ تا ۱۴', platform:'bale', url:'https://ble.ir/ostadnavaii', category:'عمومی', tags:['ورزش']},
{title:'ورزش‌های جسمی و ذهنی', subtitle:'استاد تبریزی — ۲ تا ۴', platform:'rubika', url:'https://rubika.ir/joing/BAJDEBJFH0HPMPFKCPYSAEPJQSBIBJRI', category:'عمومی', tags:['ورزش','علوم ورزشی']},

/* --- مهارت‌ها و آیین زندگی --- */
{title:'مهارت مطالعه و یادگیری', subtitle:'استاد نوشین اسدی — شنبه ۱۲ تا ۱۴، مترجمی', platform:'rubika', url:'https://rubika.ir/joing/BBHAGFHFD0DUAUWNISFDHVABUTZQMWEN', category:'عمومی', tags:['مهارت مطالعه']},
{title:'مهارت مطالعه و یادگیری', subtitle:'استاد نوشین اسدی — واتساپ با حضور استاد', platform:'whatsapp', url:'https://chat.whatsapp.com/B7ezigtiAjx4rl9em6ghsp', category:'عمومی', tags:['مهارت مطالعه']},
{title:'مهارت شنیداری و گفتاری پیشرفته', subtitle:'استاد لاله اسحق‌زاده', platform:'bale', url:'https://ble.ir/join/DdCGcKrB9p', category:'عمومی', tags:['مهارت شنیداری']},
{title:'مهارت شنیداری و گفتاری پیشرفته', subtitle:'استاد لاله اسحق‌زاده — تلگرام', platform:'telegram', url:'https://t.me/+dVtK6iQjQ85KOWVk', category:'عمومی', tags:['مهارت شنیداری']},
{title:'نگارش انگلیسی پیشرفته', subtitle:'استاد بشارتی', platform:'igap', url:'https://iGap.net/join/bqEjFDyRDiJxkppzsFDJvwKxW', category:'عمومی', tags:['نگارش']},
{title:'علوم و معارف دفاع مقدس', subtitle:'استاد خالد رحمانی', platform:'igap', url:'https://iGap.net/defa422', category:'عمومی', tags:['دفاع مقدس']},
{title:'آیین زندگی', subtitle:'استاد هنرپیشه — شنبه ۱۸ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BBHDCBFHE0AXXXNKOVGUZWLYMBGAAAUG', category:'عمومی', tags:['آیین زندگی']},
{title:'آیین زندگی', subtitle:'استاد اسلام سالاری — چهارشنبه ۱۲ تا ۱۴ (بله)', platform:'bale', url:'https://ble.ir/join/EbXvafoAvo', category:'عمومی', tags:['آیین زندگی']},
{title:'آیین زندگی', subtitle:'استاد اسلام سالاری (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBGAHFAGA0GXLFTRUVXUZMTOAWXOKHNU', category:'عمومی', tags:['آیین زندگی']},
{title:'آشنایی با قوانین کسب و کار', subtitle:'استاد فرجام خوارزمی — چهارشنبه ۱۴ تا ۱۷', platform:'eitaa', url:'https://eitaa.com/joinchat/658966283C4ddbdbc383', category:'عمومی', tags:['قوانین کسب و کار']},
{title:'مدیریت استرس', subtitle:'استاد شیرین گل کریم‌پور', platform:'rubika', url:'https://rubika.ir/joing/BBDFGIEDG0JLCZJFYXMUPFQQKTRLFFUG', category:'عمومی', tags:['مدیریت استرس']},
{title:'مهارت نرم شغلی', subtitle:'استاد قائدی — تلگرام', platform:'telegram', url:'https://t.me/+cy-XzfiJs5YzMDc0', category:'عمومی', tags:['مهارت شغلی']},
{title:'آزمایشگاه فیزیک ۱', subtitle:'استاد قانع — جمعه ۲۲ خرداد، سانس‌های ۱۰، ۱۳، ۱۶ (حضوری)', platform:'other', url:'#', category:'عمومی', tags:['فیزیک','حضوری']},
{title:'فیزیک ۲', subtitle:'استاد عالیه چمنی — دوشنبه ۸ تا ۱۱', platform:'rubika', url:'https://rubika.ir/joing/BBHBIFGIE0RNDVWTEXWJTDVRLCNYWAEH', category:'عمومی', tags:['فیزیک']},
{title:'فیزیک ۲', subtitle:'استاد پناهی', platform:'bale', url:'https://ble.ir/Fizik2Panahi', category:'عمومی', tags:['فیزیک']},

/* --- کارآفرینی --- */
{title:'کارآفرینی', subtitle:'استاد الهام مصطفائی — تمام ساعات', platform:'whatsapp', url:'https://chat.whatsapp.com/HVc68ogQ5xm8xW1gykJ8iu', category:'عمومی', tags:['کارآفرینی']},
{title:'کارآفرینی', subtitle:'گروه کلاس', platform:'telegram', url:'https://t.me/+u9QwxZB_JNM1MWVk', category:'عمومی', tags:['کارآفرینی']},
{title:'کارآفرینی', subtitle:'استاد فلورا محمدی‌زاده', platform:'rubika', url:'https://rubika.ir/joing/BBGIJACHB0OGVMYEXZYZPLCPETGNWLIP', category:'عمومی', tags:['کارآفرینی']},
{title:'کارآفرینی', subtitle:'استاد محمدی‌زاده', platform:'whatsapp', url:'https://chat.whatsapp.com/HMJuSfKjZftHMR8ba938l6', category:'عمومی', tags:['کارآفرینی']},
{title:'کارآفرینی آموزشی', subtitle:'استاد نازیلا عامری — شنبه ۱۵ تا ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BBGHGCJFC0JTJSXZSSVSIXDJRMEZPLSP', category:'عمومی', tags:['کارآفرینی']},

/* --- متفرقه عمومی --- */
{title:'خانواده در اسلام', subtitle:'استاد علی‌پور کریمی', platform:'rubika', url:'https://rubika.ir/joing/BBGHFAACB0VSZBODTPNVUSIMOMHPMGDV', category:'عمومی', tags:['خانواده']},
{title:'تربیت اخلاقی', subtitle:'استاد علی‌پور کریمی — یکشنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBGHEJIFI0SIIEEPWHSHRNRFRQZWBPTM', category:'عمومی', tags:['تربیت اخلاقی']},
{title:'منطق', subtitle:'استاد فرهنگ — سه‌شنبه ۱۲ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BBHCGAADH0NCXXLZDMKGRSJBZKJZIFEE', category:'عمومی', tags:['منطق']},
{title:'معرفت‌شناسی', subtitle:'استاد محسن محمودی', platform:'bale', url:'https://ble.ir/join/8aUdiEUZrH', category:'عمومی', tags:['معرفت‌شناسی']},
{title:'آشنایی با فلسفه اسلامی', subtitle:'استاد محسن محمودی — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHIHDBC0KWSESAGLOJWGMJRQVGNMCE', category:'عمومی', tags:['فلسفه اسلامی']},
{title:'آشنایی با فلسفه اسلامی', subtitle:'استاد محسن محمودی — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/7hFsKQg8PQ', category:'عمومی', tags:['فلسفه اسلامی']},

/* ═══════════════════════════════════════════════════════════
   🌐 زبان
   ═══════════════════════════════════════════════════════════ */
{title:'زبان ترکیبی ۱', subtitle:'استاد دهقانی', platform:'rubika', url:'https://rubika.ir/joing/BACABFJFH0TSMCGQSGAOMGAXVJHTIZJN', category:'زبان', tags:['زبان ترکیبی ۱']},
{title:'زبان ترکیبی ۱', subtitle:'استاد وفانادرنیا', platform:'rubika', url:'https://rubika.ir/joing/BACACDCAA0SZEFOGOMTWLGNYBFIOUXSX', category:'زبان', tags:['زبان ترکیبی ۱']},
{title:'زبان ترکیبی ۱', subtitle:'استاد زینلی', platform:'rubika', url:'https://rubika.ir/joing/BAHBHGEED0VMZLUKXCJJYWQPHIIYCKRV', category:'زبان', tags:['زبان ترکیبی ۱']},
{title:'زبان ترکیبی ۱', subtitle:'استاد نادرنیا — پنجشنبه ۹ تا ۱۰', platform:'rubika', url:'https://rubika.ir/joing/BBHACBCDA0IWHCCKLSYAHXDLASVVHDTW', category:'زبان', tags:['زبان ترکیبی ۱']},
{title:'زبان ترکیبی ۱', subtitle:'استاد فروغ بخش', platform:'rubika', url:'https://rubika.ir/joing/BBGDGCHCI0VSQIYJKIFQWGLTRMHYGIYF', category:'زبان', tags:['زبان ترکیبی ۱']},
{title:'زبان انگلیسی عمومی ترکیبی ۱', subtitle:'استاد فرناز فروغ بخش — بله', platform:'bale', url:'https://ble.ir/English11112', category:'زبان', tags:['زبان ترکیبی ۱']},
{title:'زبان ترکیبی ۱ — همه اساتید', subtitle:'گروه عمومی', platform:'rubika', url:'https://rubika.ir/joing/BBGHGGFGJ0LUNRQHQKVUONFLJZASLYZD', category:'زبان', tags:['زبان ترکیبی ۱']},
{title:'زبان ترکیبی ۲', subtitle:'استاد موحدی — تمام ساعت‌ها', platform:'rubika', url:'https://rubika.ir/joing/JIBJJJJF0UFVASAPMJCMNKSBAPARRAIR', category:'زبان', tags:['زبان ترکیبی ۲']},
{title:'زبان ترکیبی ۲', subtitle:'استاد زینلی — تمام ساعت‌ها', platform:'rubika', url:'https://rubika.ir/joing/JIBFBIJA0ZSSIPCKJAFNZWGBSUSKGTNN', category:'زبان', tags:['زبان ترکیبی ۲']},
{title:'زبان ترکیبی ۲', subtitle:'استاد وفانادرنیا — تمام ساعت‌ها', platform:'rubika', url:'https://rubika.ir/joing/BACACDEDD0GIFTVZVVDCVYEDHLPNEYPU', category:'زبان', tags:['زبان ترکیبی ۲']},
{title:'زبان ترکیبی ۲', subtitle:'استاد دهقانی', platform:'rubika', url:'https://rubika.ir/joing/BAAEICDBD0TTGLRMXDFCUZTNRKZONONT', category:'زبان', tags:['زبان ترکیبی ۲']},
{title:'زبان ترکیبی ۲', subtitle:'استاد نادرنیا — تمام ساعت‌ها', platform:'rubika', url:'https://rubika.ir/joing/BBHBIBEGA0BMTOXWQEVDREIFGSKPIEVH', category:'زبان', tags:['زبان ترکیبی ۲']},
{title:'زبان ترکیبی پیش', subtitle:'استاد فروغ بخش', platform:'rubika', url:'https://rubika.ir/joing/BAAICDDCA0XASUQTNGKGGMPJTZJJVJFG', category:'زبان', tags:['زبان ترکیبی پیش']},
{title:'زبان ترکیبی پیش', subtitle:'استاد وفانادرنیا', platform:'rubika', url:'https://rubika.ir/joing/BACBGBFDJ0ZVRSPYRYMZUXFHUCUCFVWX', category:'زبان', tags:['زبان ترکیبی پیش']},
{title:'زبان ترکیبی ۳', subtitle:'استاد شایان‌فر', platform:'rubika', url:'https://rubika.ir/joing/JHIIAGDG0DTTFXAITOQADXFSCQAJXNMH', category:'زبان', tags:['زبان ترکیبی ۳']},
{title:'زبان ترکیبی ۳', subtitle:'استاد اعتمادی‌پور — بله', platform:'bale', url:'https://ble.ir/join/A6xGU2DDhx', category:'زبان', tags:['زبان ترکیبی ۳']},
{title:'زبان ترکیبی ۳', subtitle:'استاد موحدی', platform:'rubika', url:'https://rubika.ir/joing/BAAEHHGIB0NTZLLNKQEOQDHEKHDHUSQE', category:'زبان', tags:['زبان ترکیبی ۳']},
{title:'زبان ترکیبی ۳', subtitle:'استاد خاطره دهقانی — تمام ساعت', platform:'rubika', url:'https://rubika.ir/joing/BBGCEHIJF0SAAHHTRHYVQTYPJEZPJYWV', category:'زبان', tags:['زبان ترکیبی ۳']},
{title:'زبان ترکیبی ۳', subtitle:'استاد علی موحدی — ترم مهر ۴۰۵۱، تمام ساعت‌ها', platform:'bale', url:'https://ble.ir/join/BkmiqbuRZu', category:'زبان', tags:['زبان ترکیبی ۳']},
{title:'زبان تخصصی ۱', subtitle:'استاد سمیه حسام — سه‌شنبه ۱۳ تا ۱۵', platform:'bale', url:'https://ble.ir/join/Eh9fJJs4wm', category:'زبان', tags:['زبان تخصصی ۱']},
{title:'زبان تخصصی ۱', subtitle:'استاد گرجی', platform:'rubika', url:'https://rubika.ir/joing/BACJJEBDB0COWPKWBHTXYUIJAISOTPHX', category:'زبان', tags:['زبان تخصصی ۱']},
{title:'زبان تخصصی ۱', subtitle:'استاد غلامپور — چهارشنبه ۱۰ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BAFEGGFCH0RTZUXTTYGPWDUHEGQIYDRX', category:'زبان', tags:['زبان تخصصی ۱']},
{title:'زبان تخصصی ۱', subtitle:'استاد حسام — سه‌شنبه ۱۳ تا ۱۵', platform:'whatsapp', url:'https://chat.whatsapp.com/HRQYKXR1dXjFDvqZdBVNeG', category:'زبان', tags:['زبان تخصصی ۱']},
{title:'زبان تخصصی ۱', subtitle:'استاد کامرانی — بله', platform:'bale', url:'https://ble.ir/join/Cwgy11d3DY', category:'زبان', tags:['زبان تخصصی ۱']},
{title:'زبان تخصصی ۱', subtitle:'استاد حسین کامرانی — ترم مهر', platform:'rubika', url:'https://rubika.ir/joing/BBFIJGJAJ0MRBJPOIYQXFYXDJFUNBOQR', category:'زبان', tags:['زبان تخصصی ۱']},
{title:'زبان تخصصی ۲', subtitle:'استاد حسام — ۱۱ تا ۱۳', platform:'rubika', url:'https://rubika.ir/joing/BAAFGJFIC0KXZNDEOALIAELZQEDGBNGX', category:'زبان', tags:['زبان تخصصی ۲']},
{title:'زبان تخصصی ۲', subtitle:'استاد آزور — چهارشنبه ۱۰ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BABBDJDDB0XIOSKSQVSICHEMJKCXCRDD', category:'زبان', tags:['زبان تخصصی ۲']},
{title:'زبان تخصصی ۲', subtitle:'استاد حسین کامرانی', platform:'bale', url:'https://ble.ir/join/23ttW4nJKd', category:'زبان', tags:['زبان تخصصی ۲']},
{title:'زبان تخصصی ۲', subtitle:'استاد کامرانی — یکشنبه ۱۳ تا ۱۵', platform:'bale', url:'https://ble.ir/zaban_13_15', category:'زبان', tags:['زبان تخصصی ۲']},
{title:'زبان تخصصی ۲', subtitle:'استاد کامرانی — دوشنبه ۱۵ تا ۱۷', platform:'bale', url:'https://ble.ir/join/7o1s5a8H24', category:'زبان', tags:['زبان تخصصی ۲']},
{title:'زبان تخصصی (متون تخصصی آموزش و پرورش)', subtitle:'استاد ضیاءالدین سالاری', platform:'rubika', url:'https://rubika.ir/joing/BBGFEBEDF0TVZHPVDLFZYIIMNKSCENTS', category:'زبان', tags:['زبان تخصصی']},
{title:'زبان خارجی', subtitle:'استاد فلورا محمدی‌زاده', platform:'rubika', url:'https://rubika.ir/joing/BBHAIJJEC0TDIOHLNWYYYTIVFBCPVICG', category:'زبان', tags:['زبان خارجی']},
{title:'پشتیبانی کلاس‌های زبان ترکیبی', subtitle:'آقای عامری — ۰۹۹۳۳۹۴۳۷۷۸', platform:'other', url:'tel:09933943778', category:'زبان', tags:['پشتیبانی']},

/* ═══════════════════════════════════════════════════════════
   💰 حسابداری
   ═══════════════════════════════════════════════════════════ */
{title:'اصول حسابداری ۱', subtitle:'استاد غلامی — یکشنبه ۶ تا ۸ عصر', platform:'rubika', url:'https://rubika.ir/joing/BBHBFFDEA0ZICNLZVXYPJSWZRGXDAVTQ', category:'حسابداری', tags:['اصول ۱']},
{title:'اصول حسابداری ۱', subtitle:'دکتر عامری — دوشنبه ۱۷ تا ۲۰', platform:'whatsapp', url:'https://chat.whatsapp.com/GM3LnDe79lh56XbKWJcEnZ', category:'حسابداری', tags:['اصول ۱']},
{title:'اصول حسابداری ۱', subtitle:'استاد بهادری — شنبه ۲ تا ۶', platform:'whatsapp', url:'https://chat.whatsapp.com/Jf6sTgJfdUu8YJDBtFubVU', category:'حسابداری', tags:['اصول ۱']},
{title:'اصول حسابداری ۲', subtitle:'استاد خشنود', platform:'rubika', url:'https://rubika.ir/joing/BBGEFJBJE0YRFKQTJESMSSCBUAXTAXPJ', category:'حسابداری', tags:['اصول ۲']},
{title:'حسابداری میانه ۱', subtitle:'استاد خشنود — سه‌شنبه ۸ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BAAFCJHEE0BUTYGQKHNBJBBIFQVSGFJX', category:'حسابداری', tags:['میانه ۱']},
{title:'حسابداری میانه ۱', subtitle:'استاد خشنود — سه‌شنبه ۱۲ تا ۱۶', platform:'rubika', url:'https://rubika.ir/joing/BBHCFIFFJ0JWZOPVQBMPJOYOQERSSOUD', category:'حسابداری', tags:['میانه ۱']},
{title:'حسابداری میانه ۱', subtitle:'استاد خشنود', platform:'rubika', url:'https://rubika.ir/joing/BBFJADHHH0EDAZGPJMBVTUNNTHNFAKVT', category:'حسابداری', tags:['میانه ۱']},
{title:'حسابداری میانه ۱', subtitle:'استاد مهدی پرورش — ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBDIIAHIJ0AWIBYTVIFZSPYDRKVNODEQ', category:'حسابداری', tags:['میانه ۱','تابستان']},
{title:'حسابداری میانه ۲', subtitle:'استاد مرتضی باوقار — سه‌شنبه ۱۴ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BAAJJJBGC0LYSQZMDHGBNNIUGYBMPTWD', category:'حسابداری', tags:['میانه ۲']},
{title:'حسابداری میانه ۲', subtitle:'استاد باوقار — سه‌شنبه ۱۳', platform:'rubika', url:'https://rubika.ir/joing/BBHCGDBFC0OMIOHXDNJGLQFLLAWBFHOQ', category:'حسابداری', tags:['میانه ۲']},
{title:'حسابداری میانه ۲', subtitle:'استاد مرتضی باوقار — ایتا', platform:'eitaa', url:'https://eitaa.com/joinchat/3752789535Cc942792c96', category:'حسابداری', tags:['میانه ۲']},
{title:'حسابداری میانه ۲', subtitle:'استاد مهدی پرورش — ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBCJHHCBC0VRPLENNOCRTNRXGBCHLHPQ', category:'حسابداری', tags:['میانه ۲','تابستان']},
{title:'حسابداری میانه ۲', subtitle:'استاد پرورش — ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBCJHHCBC0QICJBVEXHDJCKWFJJDWSVV', category:'حسابداری', tags:['میانه ۲','تابستان']},
{title:'حسابداری میانه ۲', subtitle:'استاد علی همایون — تمام تایم‌ها', platform:'rubika', url:'https://rubika.ir/joing/BBGHJDHBI0KFIAGXEZITZVIZNHQQNPZV', category:'حسابداری', tags:['میانه ۲']},
{title:'حسابرسی ۱', subtitle:'استاد نصرتی — سه‌شنبه ۱۱ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BABBEFBIJ0MSLQXQZZHPTGEJDZWYXKMI', category:'حسابداری', tags:['حسابرسی ۱']},
{title:'حسابرسی ۱', subtitle:'استاد نصرتی', platform:'rubika', url:'https://rubika.ir/joing/BBFIJHGFF0FKUGKJFYDRSXYUVHSBLQFB', category:'حسابداری', tags:['حسابرسی ۱']},
{title:'حسابرسی ۱', subtitle:'استاد مریم بهادری', platform:'rubika', url:'https://rubika.ir/joing/BBGDEAIGD0IYFYAJTTADMQJJCJIPZNRM', category:'حسابداری', tags:['حسابرسی ۱']},
{title:'حسابرسی ۱', subtitle:'استاد آل سعدی — ترم تابستان', platform:'whatsapp', url:'https://chat.whatsapp.com/Hk4NqgDGbJdG48gPCLfvxB', category:'حسابداری', tags:['حسابرسی ۱','تابستان']},
{title:'رفع اشکال حسابرسی', subtitle:'استاد نقی‌پور — دانشجویان حسابداری', platform:'bale', url:'https://ble.ir/hesabdari_bnd', category:'حسابداری', tags:['حسابرسی']},
{title:'بهایابی ۱', subtitle:'استاد موردوئی — دوشنبه ۸ تا ۱۱', platform:'rubika', url:'https://rubika.ir/joing/BAAFDBHCB0LJWMTAODMOXGGSLPRWCCRV', category:'حسابداری', tags:['بهایابی ۱']},
{title:'بهایابی ۱', subtitle:'استاد ارزانی — سه‌شنبه ۱۱ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BAAJHIEGB0SVAHSUSFEDKIYWJELBVDXL', category:'حسابداری', tags:['بهایابی ۱']},
{title:'بهایابی ۲', subtitle:'استاد موردوئی', platform:'rubika', url:'https://rubika.ir/joing/BAAEFADAI0TMRKXCDAFDLYREVFDQFAOM', category:'حسابداری', tags:['بهایابی ۲']},
{title:'بهایابی ۲', subtitle:'استاد نقی‌پور — سه‌شنبه ۱۴', platform:'bale', url:'https://ble.ir/join/EnR1EmZYn7', category:'حسابداری', tags:['بهایابی ۲']},
{title:'بهای تمام شده ۱', subtitle:'استاد همایون — دوشنبه ۱۴ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBHBDHCJA0VGAMCDUFLRDDALLLCXMYAG', category:'حسابداری', tags:['بهای تمام شده']},
{title:'بهای تمام شده ۱', subtitle:'استاد موردوئی', platform:'rubika', url:'https://rubika.ir/joing/BBFJADHFI0EEESGXEEZZEHIYBWRFECVS', category:'حسابداری', tags:['بهای تمام شده']},
{title:'مالی ۱', subtitle:'استاد صغرا رضی کاظمی — دوشنبه ۸ تا ۱۱', platform:'rubika', url:'https://rubika.ir/joing/BAAHHJJCC0BYMXKSBCRDDAMBJZTMNNUI', category:'حسابداری', tags:['مالی ۱']},
{title:'مدیریت مالی ۱', subtitle:'استاد رضی کاظمی', platform:'rubika', url:'https://rubika.ir/joing/BBFJADIDB0RMAIXTFXENDLEVGGDRJOPG', category:'حسابداری', tags:['مالی ۱']},
{title:'مدیریت مالی ۱', subtitle:'استاد چلداوی', platform:'rubika', url:'https://rubika.ir/joing/BBFJADJAA0OMCLQPIWFTXIECRYCSJYCH', category:'حسابداری', tags:['مالی ۱']},
{title:'مدیریت مالی ۱', subtitle:'استاد رضی کاظمی — دوشنبه ۸ تا ۱۱', platform:'rubika', url:'https://rubika.ir/joing/BBHDCBGIB0ZWMBQLISOWOFNZRMIGBVGS', category:'حسابداری', tags:['مالی ۱']},
{title:'مالی ۲', subtitle:'استاد حسن چلداوی — سه‌شنبه ۱۷ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BABAFIGFA0VJZIACQLMGOMAZSSQODNAA', category:'حسابداری', tags:['مالی ۲']},
{title:'مالی ۲', subtitle:'استاد رضی کاظمی — تمام تایم‌ها', platform:'rubika', url:'https://rubika.ir/joing/BBHBJAHHG0JTIUJVOLBZFKVWIEBOEXVC', category:'حسابداری', tags:['مالی ۲']},
{title:'مالی ۲', subtitle:'استاد رضی کاظمی', platform:'rubika', url:'https://rubika.ir/joing/BAAHJFDHE0YDUBJCYLFEPSEADOPUAUWU', category:'حسابداری', tags:['مالی ۲']},
{title:'مالی ۲', subtitle:'استاد مرادپور — دوشنبه ۱۴ تا ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BAAGDECFG0BLQRYULMOLJYMKQWMZJOLL', category:'حسابداری', tags:['مالی ۲']},
{title:'حسابداری صنعتی / مدیریت', subtitle:'استاد موردوئی — ترم مهر', platform:'rubika', url:'https://rubika.ir/joing/BBFIJHAGI0KWNVVHJDTNNYMZIHVFIQKE', category:'حسابداری', tags:['حسابداری مدیریت']},
{title:'حسابداری مدیریت', subtitle:'استاد بهادری — ترم تابستان', platform:'bale', url:'https://ble.ir/join/Gbe6tjMuuW', category:'حسابداری', tags:['حسابداری مدیریت','تابستان']},
{title:'حسابداری ابزار و عقود اسلامی', subtitle:'استاد پرورش', platform:'rubika', url:'https://rubika.ir/joing/BABBDDHFJ0IRSEEBLUGNWUEDZDMPMTKN', category:'حسابداری', tags:['ابزار عقود']},
{title:'حسابداری ابزار و عقود اسلامی', subtitle:'دکتر پرورش — چهارشنبه ۱۸، بله', platform:'bale', url:'https://ble.ir/join/DpyssUKggM', category:'حسابداری', tags:['ابزار عقود']},
{title:'حسابداری و حسابرسی بخش عمومی', subtitle:'استاد بهادری', platform:'rubika', url:'https://rubika.ir/joing/BAHACCGEF0EHHOWRNZTOQLCKQQCVJIQD', category:'حسابداری', tags:['بخش عمومی']},
{title:'حسابداری و حسابرسی بخش عمومی', subtitle:'استاد مریدی', platform:'bale', url:'https://ble.ir/join/CVwgr2A5sx', category:'حسابداری', tags:['بخش عمومی']},
{title:'مبانی حسابداری بخش عمومی', subtitle:'استاد مریدی — ترم مهر', platform:'rubika', url:'https://rubika.ir/joing/BBFIJHBIB0GJKEWXPGLANFUWNKRQVNSH', category:'حسابداری', tags:['بخش عمومی']},
{title:'حسابداری موارد خاص', subtitle:'مریم بهادری — شنبه ۱۸ تا ۲۰', platform:'whatsapp', url:'https://chat.whatsapp.com/CYF8xWUikWvJXACcec908n', category:'حسابداری', tags:['موارد خاص']},
{title:'کنترل داخلی و نظام راهبری', subtitle:'استاد مهدی پرورش — بله', platform:'bale', url:'https://ble.ir/kontorol0', category:'حسابداری', tags:['کنترل داخلی']},
{title:'کنترل داخلی', subtitle:'استاد مهدی پرورش — ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBDAIEJGC0FMRZPGRTJESHUABBCZQLWN', category:'حسابداری', tags:['کنترل داخلی','تابستان']},
{title:'کنترل داخلی و نظام راهبری', subtitle:'استاد پرورش — گروه واتساپ', platform:'whatsapp', url:'https://chat.whatsapp.com/DCKuiz1jHyw7j7F0i57gYG', category:'حسابداری', tags:['کنترل داخلی']},
{title:'کنترل داخلی', subtitle:'استاد مهدی پرورش — ترم تابستان (۲)', platform:'rubika', url:'https://rubika.ir/joing/BBDAIEJGC0MHTSLFKAWVLDCFWRXEOLVF', category:'حسابداری', tags:['کنترل داخلی','تابستان']},
{title:'بازار سرمایه و ابزار تأمین مالی', subtitle:'استاد رضی کاظمی — سه‌شنبه ۱۰ تا ۱۳', platform:'rubika', url:'https://rubika.ir/joing/BAAJGJAIB0QDESYXBEWUVQIHWCEUEYIK', category:'حسابداری', tags:['بازار سرمایه']},
{title:'بازار سرمایه', subtitle:'استاد رضی کاظمی — ترم مهر', platform:'rubika', url:'https://rubika.ir/joing/BBFIJHCFC0SMJMOTVHFXHTURNSQQUZYH', category:'حسابداری', tags:['بازار سرمایه']},
{title:'مدیریت سرمایه‌گذاری', subtitle:'استاد رضی کاظمی — همه تایم‌ها', platform:'rubika', url:'https://rubika.ir/joing/BAAGBDDFA0BTOFTFBBZXFMXOYBZKYTAV', category:'حسابداری', tags:['سرمایه‌گذاری']},
{title:'مدیریت سرمایه‌گذاری', subtitle:'استاد رضی کاظمی — یکشنبه ۱۰ تا ۱۲', platform:'whatsapp', url:'https://chat.whatsapp.com/FQy0nBcVuNcAAEXwuCfWFB', category:'حسابداری', tags:['سرمایه‌گذاری']},
{title:'مدیریت سرمایه‌گذاری', subtitle:'استاد طاهره خداپناه — پنجشنبه ۱۳', platform:'rubika', url:'https://rubika.ir/joing/BABDBDGHG0ZMCYDZGZKZVYZDXTNQECZU', category:'حسابداری', tags:['سرمایه‌گذاری']},
{title:'مدیریت سرمایه‌گذاری', subtitle:'استاد پیشدار — چهارشنبه ۱۶ تا ۱۸', platform:'bale', url:'https://ble.ir/join/F6PXKPLkY3', category:'حسابداری', tags:['سرمایه‌گذاری']},
{title:'مدیریت سرمایه‌گذاری', subtitle:'رضی کاظمی', platform:'rubika', url:'https://rubika.ir/joing/BBGDEAJCG0JXIELETCIVVVEWSNIATVNY', category:'حسابداری', tags:['سرمایه‌گذاری']},
{title:'تحقیق در عملیات', subtitle:'استاد پویا دانشمند', platform:'rubika', url:'https://rubika.ir/joing/BAAGDJCHC0TLEAJHRRCVJTUIUKBDEQKC', category:'حسابداری', tags:['تحقیق در عملیات']},
{title:'تنظیم و کنترل بودجه دولتی', subtitle:'استاد نگهداری — چهارشنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/JHGJGGED0CXDUNFVJVXNWANHQXPYRVCP', category:'حسابداری', tags:['بودجه']},
{title:'تنظیم و کنترل بودجه دولتی', subtitle:'استاد بتول شفیع‌زاد', platform:'rubika', url:'https://rubika.ir/joing/BBDEDEIJB0BXIPCBULDTBXJVDLIQHAYF', category:'حسابداری', tags:['بودجه']},
{title:'اصول بودجه‌ریزی دولتی', subtitle:'استاد فرخی سکل — سه‌شنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBHDCBGCJ0PIFBOKTPSFKCKHGULVBLBQ', category:'حسابداری', tags:['بودجه']},
{title:'اصول بودجه‌ریزی دولتی', subtitle:'استاد کاظمی', platform:'rubika', url:'https://rubika.ir/joing/BBFJADJGE0KJARUTJUQYFEEBSGHJUADX', category:'حسابداری', tags:['بودجه']},
{title:'نرم‌افزار کاربردی', subtitle:'استاد نصرتی — دوشنبه ساعت ۸', platform:'rubika', url:'https://rubika.ir/joing/BAAEEJHHH0ORDQDFVFVOOTIAFHMKHEWL', category:'حسابداری', tags:['نرم‌افزار']},
{title:'نرم‌افزار کاربردی', subtitle:'دوشنبه ۸ تا ۱۱ (واتساپ)', platform:'whatsapp', url:'https://chat.whatsapp.com/Cb6nwBwjFrKKHKICgxVPhR', category:'حسابداری', tags:['نرم‌افزار']},
{title:'سیستم‌های اطلاعاتی مالی', subtitle:'استاد حجت‌الله اسلامی — یکشنبه ۱۵ تا ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BBHBEDBBJ0GQNFBXIFNBYZNKOXOWYOZN', category:'حسابداری', tags:['سیستم‌های اطلاعاتی']},
{title:'مالیاتی ۱', subtitle:'استاد حمید رستمی جاز', platform:'rubika', url:'https://rubika.ir/joing/BBGFBEEGF0CQTMWOOMGEXJMAUHSXCYLS', category:'حسابداری', tags:['مالیاتی ۱']},
{title:'مالیاتی ۱', subtitle:'دکتر رستمی — چهارشنبه ۸ تا ۱۰', platform:'rubika', url:'https://rubika.ir/joing/BBHDBGBAH0SEKBRUSCNXMWOKZMGXWMJP', category:'حسابداری', tags:['مالیاتی ۱']},
{title:'مالیاتی ۲', subtitle:'استاد کارگر', platform:'whatsapp', url:'https://chat.whatsapp.com/ChmyYlpi8ESDo86t4oGQYX', category:'حسابداری', tags:['مالیاتی ۲']},
{title:'مالیاتی ۲', subtitle:'استاد کارگر — ترم مهر', platform:'rubika', url:'https://rubika.ir/joing/BBFIJGHGA0XDMWVLMBUBESUGOYVNKHUG', category:'حسابداری', tags:['مالیاتی ۲']},
{title:'مالیاتی ۲', subtitle:'استاد کامرانی — چهارشنبه ۱۶ تا ۱۸', platform:'bale', url:'https://ble.ir/join/DXZkGgwhgk', category:'حسابداری', tags:['مالیاتی ۲']},
{title:'پول و ارز و بانکداری', subtitle:'استاد افراسیابی — ترم مهر', platform:'rubika', url:'https://rubika.ir/joing/BBFIJHCCI0VXSRDVUMQRSSIUMPSMRRIA', category:'حسابداری', tags:['پول و ارز']},
{title:'پول و ارز و بانکداری', subtitle:'استاد بارانی', platform:'rubika', url:'https://rubika.ir/joing/BBDFJFDEG0JILWLDROHGXAGXGZMEVNRC', category:'حسابداری', tags:['پول و ارز']},
{title:'مباحث جاری در حسابداری', subtitle:'استاد موردوئی', platform:'rubika', url:'https://rubika.ir/joing/BBGDEAJFF0JNTZVSPNIMAMVIJXFVNJUB', category:'حسابداری', tags:['مباحث جاری']},
{title:'روش تحقیق در مدیریت', subtitle:'استاد انسیه برخورداری — یکشنبه ۱۷ تا ۲۰ (با استاد)', platform:'rubika', url:'https://rubika.ir/joing/BBHBFBJED0FDHMIWPECKJBBDGQRWDDAP', category:'حسابداری', tags:['روش تحقیق']},
{title:'روش تحقیق در مدیریت', subtitle:'استاد انسیه برخورداری — یکشنبه ۱۷ تا ۲۰ (بدون استاد)', platform:'rubika', url:'https://rubika.ir/joing/BBHBFCJDI0WRWZUPSUKYUUFEUIHFVKUJ', category:'حسابداری', tags:['روش تحقیق']},
{title:'جزوه‌ها و مطالب حسابداری', subtitle:'کانال جزوه — تلگرام', platform:'telegram', url:'https://t.me/jozve_azad_bnd1', category:'حسابداری', tags:['جزوه']},
{title:'رشته حسابداری — همه ورودی‌ها', subtitle:'گروه عمومی', platform:'rubika', url:'https://rubika.ir/joing/BAAECDJFB0LYFFPIXAXYQUDWCMJROBWG', category:'حسابداری', tags:['رشته']},

/* ═══════════════════════════════════════════════════════════
   ⚖️ حقوق
   ═══════════════════════════════════════════════════════════ */
{title:'حقوق تطبیقی', subtitle:'استاد احمد رنجبر', platform:'bale', url:'https://ble.ir/join/H6bwaxFWB2', category:'حقوق', tags:['حقوق تطبیقی']},
{title:'مدنی ۲', subtitle:'استاد ابروشن', platform:'rubika', url:'https://rubika.ir/joing/BAAFDAFGE0GZPTVDYTZSKGLCIOQOXCLX', category:'حقوق', tags:['مدنی ۲']},
{title:'مدنی ۲', subtitle:'استاد رضایی مفرد', platform:'rubika', url:'https://rubika.ir/joing/BBHAJBEEF0LORIWUMGFQOUEFAWAHDZZW', category:'حقوق', tags:['مدنی ۲']},
{title:'حقوق مدنی ۲', subtitle:'استاد سعید احمدی', platform:'rubika', url:'https://rubika.ir/joing/BBHCAABEI0SKTAKAUTCUGKCLLMLJLWLC', category:'حقوق', tags:['مدنی ۲']},
{title:'حقوق مدنی ۳', subtitle:'استاد هومن آبروشن — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/FjJqWScl7mM0fDlVPR4Ypj', category:'حقوق', tags:['مدنی ۳']},
{title:'مدنی ۴ (الزامات خارج از قرارداد)', subtitle:'استاد وظیفه‌شناس', platform:'whatsapp', url:'https://chat.whatsapp.com/IftoriTCmOoFgEf2es940t', category:'حقوق', tags:['مدنی ۴']},
{title:'مدنی ۵', subtitle:'استاد خطیب — شنبه ۱۶ تا ۱۸', platform:'whatsapp', url:'https://chat.whatsapp.com/Dr0RHX6LLsk69q3e1xgTjA', category:'حقوق', tags:['مدنی ۵']},
{title:'مدنی ۶', subtitle:'استاد رمقانی — سه‌شنبه ۱۰ تا ۱۳', platform:'whatsapp', url:'https://chat.whatsapp.com/CAC5QYCyTvNEr3YKqBHDB5', category:'حقوق', tags:['مدنی ۶']},
{title:'آیین دادرسی مدنی ۱', subtitle:'استاد مهدی هاشمی', platform:'rubika', url:'https://rubika.ir/joing/BABBIDBAI0PPSDNIFZBOPHIMZRCGIIXL', category:'حقوق', tags:['آد م ۱']},
{title:'آیین دادرسی مدنی ۱', subtitle:'استاد هاشمی', platform:'whatsapp', url:'https://chat.whatsapp.com/CelzD2nIaky44psZT1Ln8P', category:'حقوق', tags:['آد م ۱']},
{title:'آیین دادرسی مدنی ۲', subtitle:'استاد رضایی', platform:'whatsapp', url:'https://chat.whatsapp.com/FkjuxOlJBa5BirqU7XtaFN', category:'حقوق', tags:['آد م ۲']},
{title:'آیین دادرسی مدنی ۲', subtitle:'دکتر مهدی هاشمی', platform:'whatsapp', url:'https://chat.whatsapp.com/GqARh6AdJhA8T6E0mGqFgD', category:'حقوق', tags:['آد م ۲']},
{title:'آیین دادرسی مدنی ۳', subtitle:'استاد خواجویی گسمونی', platform:'rubika', url:'https://rubika.ir/joing/BAFFIGIAG0JBLDFNQLPCNWLNCBRIJSIT', category:'حقوق', tags:['آد م ۳']},
{title:'آیین دادرسی کیفری ۱', subtitle:'استاد محمدی', platform:'whatsapp', url:'https://chat.whatsapp.com/CLbHH0KfBEECjdtlA2jVxx', category:'حقوق', tags:['آد ک ۱']},
{title:'آیین دادرسی کیفری ۱', subtitle:'استاد آبروشن', platform:'whatsapp', url:'https://chat.whatsapp.com/K5WM2LBYeIZ0ZNnsvgCfCR', category:'حقوق', tags:['آد ک ۱']},
{title:'آیین دادرسی کیفری ۲', subtitle:'استاد محمدی', platform:'whatsapp', url:'https://chat.whatsapp.com/LpouAIUSYmK1ozTNpioUNg', category:'حقوق', tags:['آد ک ۲']},
{title:'جزا اختصاصی ۱', subtitle:'استاد محمدی', platform:'whatsapp', url:'https://chat.whatsapp.com/DAg0nLrIDFI3xM4f47ZT5P', category:'حقوق', tags:['جزا ۱']},
{title:'جزا اختصاصی ۱', subtitle:'استاد آبروشن', platform:'whatsapp', url:'https://chat.whatsapp.com/K8kq3aHOKLS0zdS2OWTiWM', category:'حقوق', tags:['جزا ۱']},
{title:'جزا اختصاصی ۱', subtitle:'استاد جعفری', platform:'whatsapp', url:'https://chat.whatsapp.com/BO0gYDN2t951jRw5vvQIp7', category:'حقوق', tags:['جزا ۱']},
{title:'جزای اختصاصی ۲', subtitle:'استاد علیرضا رحمانی نعیم‌آبادی', platform:'rubika', url:'https://rubika.ir/joing/BBGDAAFDE0KPTYNZXBEROMJHSVUBTORH', category:'حقوق', tags:['جزا ۲']},
{title:'جزا اختصاصی ۳', subtitle:'استاد سالاری‌فر', platform:'rubika', url:'https://rubika.ir/joing/BAADEDJFA0LYAGAANGCJZUBOFKIVRPFO', category:'حقوق', tags:['جزا ۳']},
{title:'حقوق جزا اختصاصی ۴', subtitle:'استاد رحمانی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/GCQe0D2JzFODe8x0ssJEoJ', category:'حقوق', tags:['جزا ۴']},
{title:'حقوق جزای عمومی ۱', subtitle:'استاد سیروس ضرغامی', platform:'whatsapp', url:'https://chat.whatsapp.com/F0VeaXGtfKL1Ylgj0b3YU3', category:'حقوق', tags:['جزا عمومی ۱']},
{title:'حقوق جزای عمومی ۳', subtitle:'استاد سالاری فر', platform:'whatsapp', url:'https://chat.whatsapp.com/GhEcHvBsX8JB6zOM7MVGEn', category:'حقوق', tags:['جزا عمومی ۳']},
{title:'قواعد فقه ۱', subtitle:'استاد ابراهیم کارگری', platform:'whatsapp', url:'https://chat.whatsapp.com/IrQEMmoSAn4L3CWBRTqufE', category:'حقوق', tags:['قواعد فقه ۱']},
{title:'قواعد فقه ۱', subtitle:'استاد احمدی', platform:'rubika', url:'https://rubika.ir/joing/BBDEBGGBI0VBYSYBRSROSFJQSBKWJFGN', category:'حقوق', tags:['قواعد فقه ۱']},
{title:'قواعد فقه ۲', subtitle:'استاد ابراهیم کارگری', platform:'whatsapp', url:'https://chat.whatsapp.com/DYHMGjCgKfcFEF9Hq3u44K', category:'حقوق', tags:['قواعد فقه ۲']},
{title:'قواعد فقه ۲', subtitle:'استاد خضری', platform:'rubika', url:'https://rubika.ir/joing/BAADICCHB0VFZLMZTSVKDVLMALSJUHYC', category:'حقوق', tags:['قواعد فقه ۲']},
{title:'قواعد فقه ۲', subtitle:'استاد زرند', platform:'whatsapp', url:'https://chat.whatsapp.com/IphVEzjU8Ov7YHHtDDZR9n', category:'حقوق', tags:['قواعد فقه ۲']},
{title:'قواعد فقه جزایی ۲', subtitle:'استاد ادیبی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/CaThLf3Z7RQ9bCpQhgZUEz', category:'حقوق', tags:['قواعد فقه جزایی ۲']},
{title:'قواعد فقه مدنی ۱', subtitle:'استاد ادیبی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/Kmp8IRdvRIr3Gi4nf3MJsU', category:'حقوق', tags:['قواعد فقه مدنی ۱']},
{title:'اصول فقه ۱', subtitle:'استاد یاسر روستایی', platform:'whatsapp', url:'https://chat.whatsapp.com/C3zlJ1sAdQ325q65WKUga8', category:'حقوق', tags:['اصول فقه ۱']},
{title:'اصول فقه ۱', subtitle:'دکتر ادیبی', platform:'whatsapp', url:'https://chat.whatsapp.com/EQrVOMWXTfE9ufRV6PFPm1', category:'حقوق', tags:['اصول فقه ۱']},
{title:'متون فقه ۱', subtitle:'استاد صفدری نیاک — ۱۲ تا ۱۸', platform:'whatsapp', url:'https://chat.whatsapp.com/HBfndoOBEoB9MWjxRLDxij', category:'حقوق', tags:['متون فقه ۱']},
{title:'متون فقه ۲', subtitle:'سارا ادیبی', platform:'whatsapp', url:'https://chat.whatsapp.com/IPLC2u2nGNaJtmet0oKswb', category:'حقوق', tags:['متون فقه ۲']},
{title:'متون فقه ۳', subtitle:'دکتر صفدری نیاک — یکشنبه ۱۴ تا ۱۶', platform:'whatsapp', url:'https://chat.whatsapp.com/CLqFqRWbgyI5gorLcqXyJL', category:'حقوق', tags:['متون فقه ۳']},
{title:'متون فقه ۴', subtitle:'دکتر صفدری نیاک', platform:'whatsapp', url:'https://chat.whatsapp.com/Cs8hx1HjKoG4VoJuSCVYeW', category:'حقوق', tags:['متون فقه ۴']},
{title:'متون فقه جزایی ۴', subtitle:'استاد کریمی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/Lv0nnVPkFr2FpsNx6aBYqT', category:'حقوق', tags:['متون فقه جزایی ۴']},
{title:'متون حقوقی ۱', subtitle:'استاد خاقانی', platform:'whatsapp', url:'https://chat.whatsapp.com/EuSd1I1s7XVHs0M6kJsehK', category:'حقوق', tags:['متون حقوقی ۱']},
{title:'متون حقوقی ۱', subtitle:'استاد احمدی', platform:'whatsapp', url:'https://chat.whatsapp.com/HJ0t3ISCshh9EhDmvtwXwK', category:'حقوق', tags:['متون حقوقی ۱']},
{title:'متون حقوقی ۲', subtitle:'استاد محمد رضایی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/K3Cc5nFjjiM4WmRti1iJgQ', category:'حقوق', tags:['متون حقوقی ۲']},
{title:'متون حقوقی ۳', subtitle:'استاد کمال‌نژاد — ترم تابستان', platform:'whatsapp', url:'https://chat.whatsapp.com/F3IscUVKesVK8o27n9kBRQ', category:'حقوق', tags:['متون حقوقی ۳']},
{title:'متون حقوقی ۳', subtitle:'استاد شهبازی', platform:'rubika', url:'https://rubika.ir/joing/BBDFHBBDJ0DMLXGRXPSYBCAOFPTOYVWR', category:'حقوق', tags:['متون حقوقی ۳']},
{title:'متون حقوقی ۴', subtitle:'استاد آقایان حسینی', platform:'whatsapp', url:'https://chat.whatsapp.com/IrNzFQsOLmP4wKWOFcXRoY', category:'حقوق', tags:['متون حقوقی ۴']},
{title:'حقوق بین‌الملل عمومی ۱', subtitle:'استاد احمد حاجی‌زاده', platform:'whatsapp', url:'https://chat.whatsapp.com/I5ErbI51TEb7MhrY175KkY', category:'حقوق', tags:['بین‌الملل عمومی ۱']},
{title:'حقوق بین‌الملل عمومی ۱', subtitle:'استاد شهروز دربندی', platform:'whatsapp', url:'https://chat.whatsapp.com/EJ9cp0PWo0PLsimRv7RHV3', category:'حقوق', tags:['بین‌الملل عمومی ۱']},
{title:'حقوق بین‌الملل عمومی ۲', subtitle:'استاد حاجی‌زاده', platform:'whatsapp', url:'https://chat.whatsapp.com/J3gjkscELOYGRBoXvjgeIa', category:'حقوق', tags:['بین‌الملل عمومی ۲']},
{title:'حقوق بین‌الملل عمومی ۳', subtitle:'استاد دربندی — ترم مهر', platform:'rubika', url:'https://rubika.ir/joing/BBFEBIHHC0MYMQOCRNZIRNOXPGUHKPAM', category:'حقوق', tags:['بین‌الملل عمومی ۳']},
{title:'حقوق بین‌الملل عمومی ۳', subtitle:'استاد دربندی — ترم مهر (واتساپ)', platform:'whatsapp', url:'https://chat.whatsapp.com/JvHH1MSYRtxGHP1mRS9u6F', category:'حقوق', tags:['بین‌الملل عمومی ۳']},
{title:'حقوق بین‌الملل عمومی ۳', subtitle:'گروه روبیکا (اشتراک‌گذاری)', platform:'whatsapp', url:'https://chat.whatsapp.com/IfEqkKkXfOC1SpgjKW6yfE', category:'حقوق', tags:['بین‌الملل عمومی ۳']},
{title:'حقوق بین‌الملل خصوصی ۱', subtitle:'استاد دربندی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/LaFmkzved1FD6fzMCNdvsb', category:'حقوق', tags:['بین‌الملل خصوصی ۱']},
{title:'حقوق بین‌الملل خصوصی ۱', subtitle:'استاد آقایان حسینی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/BXwKB3ZmSNYEciOzLDVPrC', category:'حقوق', tags:['بین‌الملل خصوصی ۱']},
{title:'حقوق بین‌الملل خصوصی ۱', subtitle:'استاد حاجی‌زاده', platform:'whatsapp', url:'https://chat.whatsapp.com/GxsHsXGPrXw4T6F2RYCHw1', category:'حقوق', tags:['بین‌الملل خصوصی ۱']},
{title:'حقوق سازمان‌های بین‌المللی', subtitle:'استاد دربندی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/CUbRBxfwhQcF16kIJY9z0q', category:'حقوق', tags:['سازمان‌های بین‌المللی']},
{title:'داوری بین‌المللی', subtitle:'استاد شهریاری', platform:'rubika', url:'https://rubika.ir/joing/BACDEDIIE0EZJZMGDAKJGTNVPCTAXQGI', category:'حقوق', tags:['داوری بین‌المللی']},
{title:'داوری بین‌المللی', subtitle:'استاد شهریاری — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/LFyL2QFjYqe4Ibnl4T2fwR', category:'حقوق', tags:['داوری بین‌المللی']},
{title:'حقوق تجارت ۲', subtitle:'استاد رضا رضایی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/BeLDXJMvO544b2huk00EKs', category:'حقوق', tags:['تجارت ۲']},
{title:'تجارت ۴', subtitle:'استاد رضا رضایی', platform:'whatsapp', url:'https://chat.whatsapp.com/JNqUKewC15vKIg1aw7AFZx', category:'حقوق', tags:['تجارت ۴']},
{title:'حقوق مالیه عمومی', subtitle:'استاد سلمان ستوده‌نیا — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/BXwKB3ZmSNYEciOzLDVPrC', category:'حقوق', tags:['مالیه عمومی']},
{title:'حقوق مالیه', subtitle:'استاد مهران افراسیابی', platform:'rubika', url:'https://rubika.ir/joing/BAGJFAAEB0RZNICOZFHRHVRDDSCEVCTP', category:'حقوق', tags:['مالیه']},
{title:'حقوق مالیه', subtitle:'استاد ستوده‌نیا', platform:'rubika', url:'https://rubika.ir/joing/BABBAAJGJ0GMDEWYHQTRJMQCCPFEISLH', category:'حقوق', tags:['مالیه']},
{title:'مالیه عمومی', subtitle:'استاد ستوده‌نیا — دوشنبه ۸ تا ۱۰', platform:'whatsapp', url:'https://chat.whatsapp.com/ESsrpjimLq1ECi1ucEvlZw', category:'حقوق', tags:['مالیه عمومی']},
{title:'حقوق اداری ۱', subtitle:'دکتر مطرودی', platform:'whatsapp', url:'https://chat.whatsapp.com/J0vrNP9YJj8J3cIrZj0vPO', category:'حقوق', tags:['اداری ۱']},
{title:'حقوق اساسی ۲', subtitle:'استاد اسلام رئیسی سرخونی', platform:'rubika', url:'https://rubika.ir/joing/BBHBIBEGA0BMTOXWQEVDREIFGSKPIEVH', category:'حقوق', tags:['اساسی ۲']},
{title:'پیشگیری از جرم', subtitle:'استاد زرند', platform:'rubika', url:'https://rubika.ir/joing/BAEDFDGBE0ULGMRNYIWGLBAZJVOOTICU', category:'حقوق', tags:['پیشگیری از جرم']},
{title:'جرم‌شناسی', subtitle:'استاد سایبانی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/FfJ1J3cIbOfBeRMoOPMzB3', category:'حقوق', tags:['جرم‌شناسی']},
{title:'حقوق فضای مجازی', subtitle:'استاد روستایی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/C3aK1JBQ10BKGFg3Scf6PE', category:'حقوق', tags:['فضای مجازی']},
{title:'فلسفه حقوق', subtitle:'استاد محمودی', platform:'whatsapp', url:'https://chat.whatsapp.com/EQJgwfl4JGuGFDQyrF9r1d', category:'حقوق', tags:['فلسفه حقوق']},
{title:'فلسفه حق', subtitle:'استاد محمودی', platform:'whatsapp', url:'https://chat.whatsapp.com/CMfG0wZ2naq5vcc6khbl5o', category:'حقوق', tags:['فلسفه حق']},
{title:'فلسفه حق', subtitle:'استاد محمودی (۲)', platform:'whatsapp', url:'https://chat.whatsapp.com/JrtAmscqRsdGrKze5rTM6p', category:'حقوق', tags:['فلسفه حق']},
{title:'پزشکی قانونی', subtitle:'استاد الهه محمدی — ترم مهر', platform:'whatsapp', url:'https://chat.whatsapp.com/GfRzrsv3BBPFyt9Os7PaTc', category:'حقوق', tags:['پزشکی قانونی']},
{title:'حقوق ثبت', subtitle:'استاد سراجی', platform:'whatsapp', url:'https://chat.whatsapp.com/E4hjOf2GQ1mJtZKtAesU5n', category:'حقوق', tags:['حقوق ثبت']},
{title:'حقوق بشر در اسلام', subtitle:'استاد رئیسی', platform:'rubika', url:'https://rubika.ir/joing/BBFJDHFGE0WQDSEUVQHYIAUGTSHPNEWX', category:'حقوق', tags:['حقوق بشر']},
{title:'اجرای احکام', subtitle:'استاد سعید کریمی', platform:'whatsapp', url:'https://chat.whatsapp.com/IzjJRZ7Fjuf1wQh1CLJDxC', category:'حقوق', tags:['اجرای احکام']},
{title:'کیفرشناسی', subtitle:'معصومه محمد رضائی', platform:'bale', url:'https://ble.ir/join/E8AhS1ZmVT', category:'حقوق', tags:['کیفرشناسی']},
{title:'بیان معماری ۲', subtitle:'استاد اژدری', platform:'bale', url:'https://ble.ir/join/6gE5e2xXfn', category:'حقوق', tags:['بیان معماری']},
{title:'جزوه‌های رشته حقوق', subtitle:'کانال نخبگان حقوق', platform:'rubika', url:'https://rubika.ir/Clinic_Nokhbegan_Hoghogh', category:'حقوق', tags:['جزوه']},

/* ═══════════════════════════════════════════════════════════
   📊 مدیریت و اقتصاد
   ═══════════════════════════════════════════════════════════ */
{title:'مدیریت استراتژیک', subtitle:'استاد مسعود سایانی — امتحان میان‌ترم ۷ خرداد ساعت ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BAEFEFCIE0QISAEPWELFUTMFDVGAZJVW', category:'مدیریت', tags:['مدیریت استراتژیک']},
{title:'مدیریت استراتژیک', subtitle:'دوشنبه ۱۷ تا ۱۹', platform:'whatsapp', url:'https://chat.whatsapp.com/FC4BpuLpWWE6IGSJEnDy54', category:'مدیریت', tags:['مدیریت استراتژیک']},
{title:'بازرگانی بین‌المللی', subtitle:'استاد وحید بارانی — مدیریت بازرگانی', platform:'rubika', url:'https://rubika.ir/joing/BABIBIGDC0ZZGOSNPMFMTZHYCJXJZEUX', category:'مدیریت', tags:['بازرگانی بین‌المللی']},
{title:'رفتار سازمانی', subtitle:'استاد مهرداد نظری — جمعه ۱۴ تا ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BAAFDAGBH0BZZZGYRWDXPXUGJPZPCAUL', category:'مدیریت', tags:['رفتار سازمانی']},
{title:'مدیریت رفتار سازمانی', subtitle:'استاد مهناز برخورداری احمدی — پنجشنبه ۱۷ تا ۲۰', platform:'eitaa', url:'https://eitaa.com/joinchat/1692665599C2ba51f6bc4', category:'مدیریت', tags:['رفتار سازمانی']},
{title:'مدیریت رفتار سازمانی', subtitle:'استاد مهدی دهقانی — شنبه ۱۴ تا ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BBHAHHJDJ0HRTAOGHLWYWUGFCZXNHALJ', category:'مدیریت', tags:['رفتار سازمانی']},
{title:'مدیریت کسب و کار', subtitle:'استاد رئیسی گودوئی — پنجشنبه ۱۲ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BABAEBAIC0USGZGSMVMIRXFZQZNMLDQT', category:'مدیریت', tags:['مدیریت کسب و کار']},
{title:'مبانی سازمان کسب و کار', subtitle:'استاد رئیسی — سه‌شنبه ۱۴ تا ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BBGAHEJJF0DVVACUPDDCSYXIKAMMUYMZ', category:'مدیریت', tags:['مبانی سازمان']},
{title:'مبانی سازمان کسب و کار', subtitle:'سه‌شنبه ۱۷ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BBHCHJJEH0LWKUMOXKJJIRAZFVNFZXVM', category:'مدیریت', tags:['مبانی سازمان']},
{title:'مبانی سازمان و مدیریت', subtitle:'استاد وجیهه رئیسی — چهارشنبه ۱۴', platform:'bale', url:'https://ble.ir/join/9t8tz5KzNN', category:'مدیریت', tags:['مبانی سازمان']},
{title:'مبانی سازمان مدیریت', subtitle:'استاد مهدی دهقانی — یکشنبه ۱۴ تا ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BBHBDIEED0GEVPPCNHTHCXHVJNQLJOTE', category:'مدیریت', tags:['مبانی سازمان']},
{title:'اقتصاد کلان', subtitle:'استاد کمالی — یکشنبه ۲ تا ۵', platform:'bale', url:'https://ble.ir/join/6umyD8dqBM', category:'مدیریت', tags:['اقتصاد کلان']},
{title:'اقتصاد کلان', subtitle:'استاد سلمان ستوده‌نیا — سه‌شنبه ۱۱ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BBHDBGCCE0JQBZSACGTVCMRKXYSSOHDX', category:'مدیریت', tags:['اقتصاد کلان']},
{title:'اقتصاد کلان', subtitle:'استاد نگهداری', platform:'bale', url:'https://ble.ir/join/FnTGWRnuEQ', category:'مدیریت', tags:['اقتصاد کلان']},
{title:'اقتصاد خرد', subtitle:'استاد حسین حیدری — دوشنبه ۱۳ تا ۱۶', platform:'bale', url:'https://ble.ir/join/AJjnWhDCQJ', category:'مدیریت', tags:['اقتصاد خرد']},
{title:'اقتصاد خرد', subtitle:'استاد حسین حیدری — یکشنبه ۱۴ تا ۱۷', platform:'whatsapp', url:'https://chat.whatsapp.com/DnoImIkt0K55kHsEpie5CQ', category:'مدیریت', tags:['اقتصاد خرد']},
{title:'اقتصاد خرد', subtitle:'استاد حسین حیدری — دوشنبه ۱۳ تا ۱۶ (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BAAFDBCEE0FDXDISWXBBUQBBSKPBTATH', category:'مدیریت', tags:['اقتصاد خرد']},
{title:'اقتصاد (خرد و کلان)', subtitle:'استاد حسین حیدری — سه‌شنبه ۱۳ تا ۱۶', platform:'bale', url:'https://ble.ir/join/FoNVHHsijb', category:'مدیریت', tags:['اقتصاد']},
{title:'اقتصاد خرد', subtitle:'ابراهیم نگهداری', platform:'bale', url:'https://ble.ir/eghtesadkhord1405', category:'مدیریت', tags:['اقتصاد خرد']},
{title:'آمار و کاربرد آن در مدیریت مالی', subtitle:'استاد علیرضا سالارزاده — چهارشنبه ۸ تا ۱۱', platform:'rubika', url:'https://rubika.ir/joing/BBHDBFCEA0HGYILYOALZWDDFMNWXQOTN', category:'مدیریت', tags:['آمار']},
{title:'ریاضیات و کاربرد آن در مدیریت ۱', subtitle:'استاد بهزادی — دوشنبه ۱۴ تا ۱۷', platform:'rubika', url:'https://rubika.ir/joing/BABJBGBGH0EIVSSAWQVUVBTMQCHBLYKS', category:'مدیریت', tags:['ریاضی']},
{title:'روش تحقیق', subtitle:'استاد محمدی‌زاده', platform:'rubika', url:'https://rubika.ir/joing/BBHBBJIIB0AIBDQNDTQLNQTVJVWRIYFB', category:'مدیریت', tags:['روش تحقیق']},
{title:'روش تحقیق', subtitle:'استاد جوادی‌زاده — سه‌شنبه ۱۲ تا ۱۵', platform:'whatsapp', url:'https://chat.whatsapp.com/LSR9BYKZsIY1W4vY1qXxZ2', category:'مدیریت', tags:['روش تحقیق']},
{title:'روش تحقیق (کمی و کیفی)', subtitle:'استاد خلیل آریا', platform:'rubika', url:'https://rubika.ir/joing/BBGEIFFHB0EOWSTQESLCDIRJSLCZPLVL', category:'مدیریت', tags:['روش تحقیق']},
{title:'روش تحقیق', subtitle:'استاد شهبازی — تابستان', platform:'whatsapp', url:'https://chat.whatsapp.com/K7Z10e9RZnU5nHDJodgj53', category:'مدیریت', tags:['روش تحقیق','تابستان']},
{title:'تحقیق در عملیات', subtitle:'استاد مهناز برخورداری — سه‌شنبه ۸ تا ۱۱ و ۱۱ تا ۱۴', platform:'whatsapp', url:'https://chat.whatsapp.com/HDAUFWpDpkyEhuVLeeZa8E', category:'مدیریت', tags:['تحقیق در عملیات']},

/* ═══════════════════════════════════════════════════════════
   💻 کامپیوتر و فنی-مهندسی
   ═══════════════════════════════════════════════════════════ */
{title:'برنامه‌سازی کامپیوتر', subtitle:'استاد آبادیان — برق و مهندسی', platform:'rubika', url:'https://rubika.ir/joing/BAIHIBFAD0NYUVBWFAKOSXZYJVWBBAUA', category:'کامپیوتر', tags:['برنامه‌سازی']},
{title:'طراحی کامپایلر', subtitle:'استاد لطفی', platform:'rubika', url:'https://rubika.ir/joing/BAIGAFBHA0NBCDFAFOABRWGRAQDRSAZV', category:'کامپیوتر', tags:['کامپایلر']},
{title:'معماری کامپیوتر', subtitle:'استاد حافظی', platform:'rubika', url:'https://rubika.ir/joinc/EICEBEDB0OFMRVOTTZIZNDQUSRGHDQSO', category:'کامپیوتر', tags:['معماری']},
{title:'سیستم‌عامل', subtitle:'استاد شایسته — مهر ۴۰۵', platform:'telegram', url:'https://t.me/+-L_g_IW7GNBkODg8', category:'کامپیوتر', tags:['سیستم‌عامل']},
{title:'برنامه‌نویسی سیستم', subtitle:'استاد شایسته', platform:'rubika', url:'https://rubika.ir/joing/BBHAGDJBE0QJOTWTRWCLJASSTRJTTYOH', category:'کامپیوتر', tags:['برنامه‌نویسی سیستم']},
{title:'داده‌کاوی', subtitle:'استاد اعظم قائدی — مهر ۴۰۵', platform:'telegram', url:'https://t.me/+kEaw3SZ36mo3MDQ0', category:'کامپیوتر', tags:['داده‌کاوی']},
{title:'آزمایشگاه نرم‌افزارهای اداری', subtitle:'استاد مینا بهرامی', platform:'bale', url:'https://ble.ir/narmafzar_edari', category:'کامپیوتر', tags:['حسابداری']},
{title:'ریاضی مهندسی', subtitle:'استاد رمضان‌نیا — چهارشنبه ۱۱ تا ۱۴', platform:'telegram', url:'https://t.me/+fSmHM2qeppk5ZGE0', category:'کامپیوتر', tags:['ریاضی مهندسی']},
{title:'محاسبات عددی', subtitle:'استاد ناصر پناهی — سه‌شنبه ۸ تا ۱۰', platform:'rubika', url:'https://rubika.ir/joing/BBFJIHIBH0OCDFOEAWYIZXMKBUILLWIL', category:'کامپیوتر', tags:['محاسبات عددی']},
{title:'محاسبات عددی', subtitle:'استاد جلالی‌نژاد', platform:'bale', url:'https://ble.ir/join/E48ERFiGqe', category:'کامپیوتر', tags:['محاسبات عددی']},
{title:'معادلات دیفرانسیل', subtitle:'استاد رمضان‌نیا — چهارشنبه ۸ تا ۱۱', platform:'telegram', url:'https://t.me/+yeuUqDIlp0A0YTE0', category:'کامپیوتر', tags:['معادلات دیفرانسیل']},
{title:'معادلات دیفرانسیل', subtitle:'استاد جواهری', platform:'rubika', url:'https://rubika.ir/joing/BBDAHGAEJ0MQPFEATZHTIFRBBCNMIROH', category:'کامپیوتر', tags:['معادلات دیفرانسیل']},
{title:'ترمودینامیک ۱', subtitle:'استاد محسنی — سه‌شنبه', platform:'rubika', url:'https://rubika.ir/joing/BBHCFCGBG0QQYLWYNDEBJSAGOLUWZBNN', category:'کامپیوتر', tags:['ترمودینامیک ۱']},
{title:'ترمودینامیک ۲', subtitle:'فاطمه السادات محسنی — سه‌شنبه ۱۱ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BBFJIHJIJ0UBCXFXUVCLRLDFOGFSVCYX', category:'کامپیوتر', tags:['ترمودینامیک ۲']},
{title:'انتقال حرارت ۱', subtitle:'اکرم عاطفی دزقی — جمعه ۱۰ تا ۱۳', platform:'rubika', url:'https://rubika.ir/joing/BBFJIHHBE0PSCOYRWNATFOPTOYRTWSDA', category:'کامپیوتر', tags:['انتقال حرارت']},
{title:'مکانیک سیالات ۱', subtitle:'اکرم عاطفی دزقی — جمعه ۱۳ تا ۱۶', platform:'rubika', url:'https://rubika.ir/joing/BBFJIFJFA0BTGHLKNJLBRVFRDBGZFRKU', category:'کامپیوتر', tags:['مکانیک سیالات']},
{title:'موازنه انرژی و مواد', subtitle:'معین‌پور — دوشنبه ۸ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BBHAFFDDF0XUREPOCQZVALYPSOYFDUPD', category:'کامپیوتر', tags:['موازنه انرژی']},
{title:'شیمی آلی', subtitle:'استاد اسفندیاری', platform:'rubika', url:'https://rubika.ir/joing/BBHAFFDIA0KGOUKRHZPHAKCSRAYDKEWG', category:'کامپیوتر', tags:['شیمی آلی']},
{title:'شیمی تجزیه', subtitle:'فرید معینی‌پور — دوشنبه ۱۲ تا ۱۵', platform:'rubika', url:'https://rubika.ir/joing/BBFJIIBCI0NHVOAVGYXIUFOURIVLXJTV', category:'کامپیوتر', tags:['شیمی تجزیه']},
{title:'سینتیک و طراحی رآکتور', subtitle:'آرش کدپور — یکشنبه ۵ تا ۹', platform:'rubika', url:'https://rubika.ir/joing/BBFJIICEA0RHUDEZKDOIYHRTYDVQRMTA', category:'کامپیوتر', tags:['سینتیک و رآکتور']},
{title:'آزمایشگاه مکانیک خاک', subtitle:'استاد آرش غلامی — تمام ساعات', platform:'bale', url:'https://ble.ir/join/HWAk8PfjZD', category:'کامپیوتر', tags:['عمران']},
{title:'نقشه‌برداری عملیات', subtitle:'استاد دادرس — ۱۴ تا ۱۷', platform:'bale', url:'https://ble.ir/join/54EBhQi7pG', category:'کامپیوتر', tags:['عمران']},
{title:'ریاضیات گسسته', subtitle:'استاد محمدحسین اسدیان — دوشنبه ۱۷ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BBHCCIGJH0BTWTFZUEYPNCEGMODERBYZ', category:'کامپیوتر', tags:['ریاضی گسسته']},
{title:'جبر خطی', subtitle:'استاد نادیا پیش‌دار', platform:'whatsapp', url:'https://chat.whatsapp.com/EHIQIrAMMD4D8cXBVcKgfa', category:'کامپیوتر', tags:['جبر خطی']},
{title:'جبر خطی', subtitle:'استاد نادیا پیش‌دار — یکشنبه ۸ تا ۱۰ (بله)', platform:'bale', url:'https://ble.ir/join/8nNnCmBxMK', category:'کامپیوتر', tags:['جبر خطی']},
{title:'جبر خطی', subtitle:'استاد پیش‌دار', platform:'rubika', url:'https://rubika.ir/joing/BBDEDHABA0XZZEUTOYDKUXVOLGSVWRYS', category:'کامپیوتر', tags:['جبر خطی']},
{title:'ریاضی عمومی ۲', subtitle:'سجاد کرمی', platform:'rubika', url:'https://rubika.ir/joing/BBDEGDBEJ0AVAPNMSITNWSLDEBVSXNAV', category:'کامپیوتر', tags:['ریاضی عمومی ۲']},
{title:'ریاضی کاربردی', subtitle:'استاد عباسلو', platform:'rubika', url:'https://rubika.ir/joing/BBHBCCABG0YJAJWXOOTCIEAKFKYIMSAV', category:'کامپیوتر', tags:['ریاضی کاربردی']},
{title:'مقدمات ۲', subtitle:'سحر زراعی — ۱۶ تا ۲۱', platform:'whatsapp', url:'https://chat.whatsapp.com/Dc9WZl4A5paJ8CHjoWEjQz', category:'کامپیوتر', tags:['مقدمات ۲']},
{title:'مقدمات ۲', subtitle:'استاد شاه‌کرمی‌پور', platform:'whatsapp', url:'https://chat.whatsapp.com/KsyMGSbpQ5MBJN6gxRuFe1', category:'کامپیوتر', tags:['مقدمات ۲']},
{title:'معماری اسلامی ۱', subtitle:'روز یکشنبه — رشته معماری', platform:'bale', url:'https://ble.ir/join/9P2C8uRfCX', category:'کامپیوتر', tags:['معماری']},
{title:'گروه رشته معماری', subtitle:'تمام مقاطع و ورودی‌ها', platform:'telegram', url:'https://t.me/+-qNvfHwSwHQ2Y2I8', category:'کامپیوتر', tags:['معماری']},
{title:'گروه واتساپ رشته برق', subtitle:'دانشجویان برق', platform:'whatsapp', url:'https://chat.whatsapp.com/KMUSFMFqPt9BAjjXOGc9zb', category:'کامپیوتر', tags:['برق']},
{title:'کانال اطلاع‌رسانی', subtitle:'اسماعیل پاک‌نژاد', platform:'rubika', url:'https://rubika.ir/unipaknejad', category:'کامپیوتر', tags:['کانال']},

/* ═══════════════════════════════════════════════════════════
   🧠 روانشناسی و علوم تربیتی
   ═══════════════════════════════════════════════════════════ */
{title:'روانشناسی تربیتی', subtitle:'دکتر پنداشته — تمام ساعات، تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBCIFCEAC0BFGJWAPEDMTTUAZESRYVWY', category:'روانشناسی', tags:['روانشناسی تربیتی','تابستان']},
{title:'روانشناسی تربیتی', subtitle:'دکتر پنداشته — تمام ساعات، بله', platform:'bale', url:'https://ble.ir/join/2aH91hqTT1', category:'روانشناسی', tags:['روانشناسی تربیتی']},
{title:'روانشناسی تربیتی', subtitle:'استاد سحر جعفری — تمام ساعات', platform:'whatsapp', url:'https://chat.whatsapp.com/I4wKXcskSn00GCtNhebXjE', category:'روانشناسی', tags:['روانشناسی تربیتی']},
{title:'روانشناسی تربیتی', subtitle:'استاد سحر جعفری — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/ELD4qzrfv3', category:'روانشناسی', tags:['روانشناسی تربیتی']},
{title:'روانشناسی تربیتی', subtitle:'استاد سحر جعفری — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHEHDDE0ZTDMHFNWICVRTZFPVFZMKT', category:'روانشناسی', tags:['روانشناسی تربیتی']},
{title:'فلسفه علم روانشناسی', subtitle:'دکتر محسن محمودی — تابستان، تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBCIDBBJG0UBGPGOZKMYEAZRONYURFYV', category:'روانشناسی', tags:['فلسفه علم','تابستان']},
{title:'فلسفه علم روانشناسی', subtitle:'دکتر محسن محمودی — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHFHIAI0IINXUNXWETDIKHXPNLMCYD', category:'روانشناسی', tags:['فلسفه علم']},
{title:'فلسفه علم روانشناسی', subtitle:'دکتر محسن محمودی — بله', platform:'bale', url:'https://ble.ir/join/GyLL1ENh3o', category:'روانشناسی', tags:['فلسفه علم']},
{title:'روانشناسی تحولی ۲', subtitle:'دکتر آزیتا امیرفخرایی — تابستان، تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBCIDBFBA0NUOYWPHMTUUWABTIGBAVPO', category:'روانشناسی', tags:['روانشناسی تحولی ۲','تابستان']},
{title:'روانشناسی تحولی ۲', subtitle:'استاد سپیده پنداشته — تمامی ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBGECJJIF0EHCYXUQSBGEWYRMRTECFVG', category:'روانشناسی', tags:['روانشناسی تحولی ۲']},
{title:'روانشناسی دین', subtitle:'استاد اکرم درودی — تابستان، تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/AEJRMp2qfA', category:'روانشناسی', tags:['روانشناسی دین','تابستان']},
{title:'روانشناسی دین', subtitle:'استاد سکینه زارعی — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHFIAIE0LAOAPKRVKDKAOHDCOMXMIT', category:'روانشناسی', tags:['روانشناسی دین']},
{title:'روانشناسی دین', subtitle:'استاد سکینه زارعی — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/4XRBn38oTX', category:'روانشناسی', tags:['روانشناسی دین']},
{title:'روانشناسی دین — چهارشنبه ۱۰ تا ۱۲', subtitle:'استاد زارعی', platform:'rubika', url:'https://rubika.ir/joing/BBEHFHGHI0QFBEVBVLRNKPCFQBOKZADN', category:'روانشناسی', tags:['روانشناسی دین']},
{title:'روانشناسی دین — چهارشنبه ۱۲ تا ۱۴', subtitle:'استاد زارعی', platform:'rubika', url:'https://rubika.ir/joing/BBHDCIHCJ0ERBKFTDIEQAOYJORUBQCYB', category:'روانشناسی', tags:['روانشناسی دین']},
{title:'روانشناسی دین — چهارشنبه ۱۴ تا ۱۶', subtitle:'استاد زارعی', platform:'rubika', url:'https://rubika.ir/joing/BBHDCIIIA0HGAXUFOOPQEOATPEBUTQNF', category:'روانشناسی', tags:['روانشناسی دین']},
{title:'روانشناسی شخصیت', subtitle:'مینا نیروکار', platform:'rubika', url:'https://rubika.ir/joing/BBGHHBIFI0BEDSHONHUNSUUYJRRTCFKG', category:'روانشناسی', tags:['روانشناسی شخصیت']},
{title:'روانشناسی شخصیت', subtitle:'استاد عبدالرضا محبی — تمامی ساعات (بله)', platform:'bale', url:'https://ble.ir/join/2JGWxpWKwJ', category:'روانشناسی', tags:['روانشناسی شخصیت']},
{title:'روانشناسی شخصیت', subtitle:'استاد عبدالرضا محبی — تمامی ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHEHDJD0IJRHROQAWMGKMTPMIHRKDQ', category:'روانشناسی', tags:['روانشناسی شخصیت']},
{title:'روانشناسی شخصیت', subtitle:'استاد یونس دریوش', platform:'rubika', url:'https://rubika.ir/joing/BBGHEEAFD0NPVPVPPTSUMWAUXMPQBFKD', category:'روانشناسی', tags:['روانشناسی شخصیت']},
{title:'روانشناسی سالمندی', subtitle:'زهرا معلم زادگان — چهارشنبه ۱۰ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BBGHGFFFG0KWNSZYSEKSKOMKPGGTIJDY', category:'روانشناسی', tags:['روانشناسی سالمندی']},
{title:'روانشناسی صنعتی سازمانی', subtitle:'استاد علیرضا روشن‌ضمیر — چهارشنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBGHGGAEB0AJJJHICGRNOYADZWSWBISV', category:'روانشناسی', tags:['روانشناسی صنعتی']},
{title:'نظریه‌های مشاوره و روان‌درمانی', subtitle:'استاد محمودی نودژ — چهارشنبه ۱۸ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BBGHGGBJA0TFFYBMEBPFOWYVQOFXCOCF', category:'روانشناسی', tags:['نظریه‌های مشاوره']},
{title:'نظریه‌های مشاوره و روان‌درمانی', subtitle:'استاد محبی', platform:'rubika', url:'https://rubika.ir/joing/BBEHHBJFC0EDHWKOZVEYFISGSWSIQALU', category:'روانشناسی', tags:['نظریه‌های مشاوره']},
{title:'نظریه‌های مشاوره و روان‌درمانی', subtitle:'استاد محبی — بله', platform:'bale', url:'https://ble.ir/join/8p1WH4PqTU', category:'روانشناسی', tags:['نظریه‌های مشاوره']},
{title:'آموزه‌های روانشناختی در قرآن', subtitle:'استاد ماریه اسمعیلی — تمام تایم‌ها', platform:'bale', url:'https://ble.ir/join/24iSyYDx1Y', category:'روانشناسی', tags:['آموزه روانشناختی']},
{title:'آسیب‌شناسی روانی کودک و نوجوان', subtitle:'استاد سحر جعفری — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/7B7YHKDrWX', category:'روانشناسی', tags:['آسیب‌شناسی کودک']},
{title:'آسیب‌شناسی روانی کودک و نوجوان', subtitle:'استاد سحر جعفری — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHEHECD0ASBOWWMYLAMHQWZDLUDXOT', category:'روانشناسی', tags:['آسیب‌شناسی کودک']},
{title:'آسیب‌شناسی روانی کودک و نوجوان', subtitle:'استاد جعفری — تمام ساعات', platform:'whatsapp', url:'https://chat.whatsapp.com/Ba8PUSF6tNt0uDpxGBmbLr', category:'روانشناسی', tags:['آسیب‌شناسی کودک']},
{title:'آسیب‌شناسی روانی کودک و نوجوان', subtitle:'استاد معلم زادگان — تمامی ساعات', platform:'bale', url:'https://ble.ir/join/3YymxgkVqk', category:'روانشناسی', tags:['آسیب‌شناسی کودک']},
{title:'آسیب‌شناسی ۱', subtitle:'استاد ندا پگاه — تمامی ساعات (بله)', platform:'bale', url:'https://ble.ir/join/5TZvvWbcEz', category:'روانشناسی', tags:['آسیب‌شناسی ۱']},
{title:'آسیب‌شناسی ۱', subtitle:'استاد ندا پگاه — تمامی ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHEIDGA0LYIQDWBQOEKIJAUSZIZJVW', category:'روانشناسی', tags:['آسیب‌شناسی ۱']},
{title:'آسیب‌شناسی ۱', subtitle:'استاد ندا پگاه — واتساپ', platform:'whatsapp', url:'https://chat.whatsapp.com/EXhV0WS4uE04O30LN4BLNz', category:'روانشناسی', tags:['آسیب‌شناسی ۱']},
{title:'آسیب‌شناسی ۲', subtitle:'استاد مجید عزیزی — تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBGEAGDBE0ODWAZWZSGSGSSVVDIDYNGQ', category:'روانشناسی', tags:['آسیب‌شناسی ۲']},
{title:'آسیب‌شناسی ۲', subtitle:'استاد ندا پگاه — تمامی ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHHAJAC0KDAPVTFIUWDCHPQUCUZRQN', category:'روانشناسی', tags:['آسیب‌شناسی ۲']},
{title:'آسیب‌شناسی ۲', subtitle:'استاد ندا پگاه — واتساپ', platform:'whatsapp', url:'https://chat.whatsapp.com/EfXAjzGJsK429HWIrtLgS4', category:'روانشناسی', tags:['آسیب‌شناسی ۲']},
{title:'روانشناسی کودکان با نیاز ویژه ۱', subtitle:'استاد مجتبی محمودی نودژ — پنجشنبه ۲ تا ۴ و ۱۲ تا ۲ (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHEGHBH0CCQEJREBSKWVCGSPQUPNAE', category:'روانشناسی', tags:['نیاز ویژه']},
{title:'روانشناسی کودکان با نیاز ویژه ۱', subtitle:'استاد مجتبی محمودی نودژ — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/6rxQNNsWxp', category:'روانشناسی', tags:['نیاز ویژه']},
{title:'روانشناسی کودکان با نیاز ویژه ۱', subtitle:'دکتر معلم زادگان — تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBGABFJCJ0LJYWFEDSQPLWNPMDYFNUZZ', category:'روانشناسی', tags:['نیاز ویژه']},
{title:'روانشناسی کودکان با نیاز ویژه ۱', subtitle:'استاد محمد زارع زاده — تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBGEAGCEA0NYZCFZPDUUJTQMUATUOCPO', category:'روانشناسی', tags:['نیاز ویژه']},
{title:'روانشناسی شناختی', subtitle:'دکتر روشن‌ضمیر — تمام ساعت', platform:'rubika', url:'https://rubika.ir/joing/BBEIFBEFG0NVNFDLDVJMDYBOQPANQTHX', category:'روانشناسی', tags:['روانشناسی شناختی']},
{title:'روانشناسی فیزیولوژیک', subtitle:'دکتر خاتمی — تمام ساعت', platform:'rubika', url:'https://rubika.ir/joing/BBEHGDJGE0EOHVUQVOEQJMABWPKJPYWX', category:'روانشناسی', tags:['فیزیولوژیک']},
{title:'روانشناسی تجربی', subtitle:'استاد مجید عزیزی — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHEHCIA0VLIRCCTQVZRAMRAWINRJFB', category:'روانشناسی', tags:['روانشناسی تجربی']},
{title:'روانشناسی تجربی', subtitle:'استاد مجید عزیزی — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/3zYZdJPHUe', category:'روانشناسی', tags:['روانشناسی تجربی']},
{title:'انگیزش و هیجان', subtitle:'استاد سارا نقیب حسینی — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/JDHk8H3n3u', category:'روانشناسی', tags:['انگیزش و هیجان']},
{title:'انگیزش و هیجان', subtitle:'استاد سارا نقیب حسینی — تمام ساعات (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHEHDAF0VKGZXOKASHDIZWLZFLCTNM', category:'روانشناسی', tags:['انگیزش و هیجان']},
{title:'متون روانشناسی به انگلیسی ۱', subtitle:'استاد نادرنیا — شنبه ۲ تا ۴', platform:'rubika', url:'https://rubika.ir/joing/BBGDBACDH0FRNYPFQFKRXIHKEFDAMLDP', category:'روانشناسی', tags:['متون روانشناسی ۱']},
{title:'متون روانشناسی به انگلیسی ۱', subtitle:'استاد نادرنیا — شنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBHAICHEB0MVCFGAMOJJNSGAZBSMLUKB', category:'روانشناسی', tags:['متون روانشناسی ۱']},
{title:'متون روانشناسی به انگلیسی ۱', subtitle:'استاد فضل‌الله صمیمی — دوشنبه ۱۴ تا ۱۶', platform:'rubika', url:'https://rubika.ir/joing/BBGCGEBCI0STKIIHAROHQIROHUXYWMEN', category:'روانشناسی', tags:['متون روانشناسی ۱']},
{title:'متون روانشناسی به انگلیسی ۲', subtitle:'استاد فضل‌الله صمیمی — تمام ساعات (واتساپ)', platform:'whatsapp', url:'https://chat.whatsapp.com/GOCCui44ydZIMWZzW8xroZ', category:'روانشناسی', tags:['متون روانشناسی ۲']},
{title:'متون روانشناسی به انگلیسی ۲', subtitle:'استاد فضل‌الله صمیمی (بله)', platform:'bale', url:'https://ble.ir/join/DLaY3CvgGs', category:'روانشناسی', tags:['متون روانشناسی ۲']},
{title:'متون روانشناسی به انگلیسی ۲', subtitle:'استاد فضل‌الله صمیمی (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHEHCEJ0JMVZASVYZCIPKMKCUCOGLA', category:'روانشناسی', tags:['متون روانشناسی ۲']},
{title:'روانشناسی رفتار مصرف‌کننده', subtitle:'استاد عباس براهیمی قلعه‌قاضی — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/HS3MFSZor2', category:'روانشناسی', tags:['رفتار مصرف‌کننده']},
{title:'روانشناسی رفتار مصرف‌کننده', subtitle:'استاد عباس براهیمی قلعه‌قاضی (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHEHDGC0OVNZVSTCYFGAKKHNNJGJDJ', category:'روانشناسی', tags:['رفتار مصرف‌کننده']},
{title:'روانشناسی مصرف‌کننده', subtitle:'استاد کریم‌نیا — بله', platform:'bale', url:'https://ble.ir/karimniyaaravan', category:'روانشناسی', tags:['مصرف‌کننده']},
{title:'روانشناسی مصرف‌کننده', subtitle:'استاد کریم‌نیا — بله (۲)', platform:'bale', url:'https://ble.ir/karimniyaa', category:'روانشناسی', tags:['مصرف‌کننده']},
{title:'آسیب‌شناسی اجتماعی', subtitle:'استاد علی رئیسی — ترم مهر', platform:'rubika', url:'https://rubika.ir/joing/BBFIGJAED0QPLQMXHFGOLDFZIDDSUKJG', category:'روانشناسی', tags:['آسیب اجتماعی']},
{title:'روانشناسی اجتماعی کاربردی', subtitle:'استاد علی رئیسی', platform:'whatsapp', url:'https://chat.whatsapp.com/GaPRLFJP4zH92sBzCovpNa', category:'روانشناسی', tags:['روانشناسی اجتماعی']},
{title:'روانشناسی اجتماعی ۲', subtitle:'استاد ابراهیمی (بله)', platform:'bale', url:'https://ble.ir/join/4vxMBPDKdA', category:'روانشناسی', tags:['روانشناسی اجتماعی ۲']},
{title:'روانشناسی اجتماعی ۲', subtitle:'استاد ابراهیمی (واتساپ)', platform:'whatsapp', url:'https://chat.whatsapp.com/GlgjCiSXmGr2My9Id32OBY', category:'روانشناسی', tags:['روانشناسی اجتماعی ۲']},
{title:'روانشناسی اجتماعی', subtitle:'استاد علی رئیسی — جمعه ۱۲ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BBGCGEBCI0STKIIHAROHQIROHUXYWMEN', category:'روانشناسی', tags:['روانشناسی اجتماعی']},
{title:'روانشناسی اجتماعی', subtitle:'استاد علی رئیسی — پنجشنبه ۱۴', platform:'whatsapp', url:'https://chat.whatsapp.com/E4I8DNVJvsD9HO4NqfX5BZ', category:'روانشناسی', tags:['روانشناسی اجتماعی']},
{title:'ارتباط انسانی', subtitle:'استاد علی رئیسی — شنبه ۱۶', platform:'whatsapp', url:'https://chat.whatsapp.com/L7GtSkGjNd2B7gtTTuGcD', category:'روانشناسی', tags:['ارتباط انسانی']},
{title:'تربیت رسانه‌ای', subtitle:'استاد علی رئیسی — شنبه ۱۸', platform:'whatsapp', url:'https://chat.whatsapp.com/DeGTbkWiQbl4TiQ9NINdgt', category:'روانشناسی', tags:['تربیت رسانه']},
{title:'روانشناسی اجتماعی کاربردی', subtitle:'استاد براهیمی (بله)', platform:'bale', url:'https://ble.ir/barahimi2', category:'روانشناسی', tags:['روانشناسی اجتماعی']},
{title:'روانشناسی اجتماعی کاربردی', subtitle:'استاد براهیمی (بله ۲)', platform:'bale', url:'https://ble.ir/join/Du6uV3ehJD', category:'روانشناسی', tags:['روانشناسی اجتماعی']},
{title:'روانشناسی اجتماعی کاربردی', subtitle:'استاد براهیمی (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBGEDAHAB0GREJPYYSNMSBPFRDNTWWQW', category:'روانشناسی', tags:['روانشناسی اجتماعی']},
{title:'روانشناسی یادگیری', subtitle:'استاد امید تراهی — شنبه ۱۸ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BBGHGDADA0UIXAJFRUNZOVVERTOJCEQC', category:'روانشناسی', tags:['روانشناسی یادگیری']},
{title:'روانشناسی یادگیری', subtitle:'استاد سکینه زارعی — چهارشنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBGCEDDHJ0ZYKYHSEOOFHOAUEQOXWHAK', category:'روانشناسی', tags:['روانشناسی یادگیری']},
{title:'روانشناسی یادگیری', subtitle:'استاد سمیه زارع — پنجشنبه ۱۴ تا ۱۶', platform:'bale', url:'https://ble.ir/join/dL4gzrGCR9', category:'روانشناسی', tags:['روانشناسی یادگیری']},
{title:'آموزش در سازمان‌ها', subtitle:'استاد ناهید سلطانی — یکشنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBGHGDBAE0PXQQNYMOBHEDSMGIOREABR', category:'روانشناسی', tags:['آموزش سازمان‌ها']},
{title:'آموزش در سازمان‌ها', subtitle:'استاد ضیاءالدین سالاری', platform:'rubika', url:'https://rubika.ir/joing/BBDECFAAB0CRNJDHTEFKPBPXTFADKSQS', category:'روانشناسی', tags:['آموزش سازمان‌ها']},
{title:'اختلال‌های رفتاری و هیجانی', subtitle:'استاد اکرم درودی — دوشنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBGHGDBIE0XUUJVGMSJZOUGOBJPQLIXC', category:'روانشناسی', tags:['اختلال رفتاری']},
{title:'برنامه‌ریزی درسی دوره متوسطه', subtitle:'استاد حسن‌زاده — چهارشنبه ۱۰ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BBGHGDCIG0JOLBYQHTQLHQSYSCWZRFDG', category:'روانشناسی', tags:['برنامه‌ریزی']},
{title:'روانشناسی سلامت', subtitle:'استاد اکرم درودی — چهارشنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBGHGDDFB0GCAUVCOFWXWZXUUPBLAMGH', category:'روانشناسی', tags:['روانشناسی سلامت']},
{title:'روانشناسی سلامت', subtitle:'استاد شیرین گل کریم‌پور', platform:'rubika', url:'https://rubika.ir/joing/BBDCAHDGJ0TMAXTXZLNYMYVHGMMAMDXW', category:'روانشناسی', tags:['روانشناسی سلامت']},
{title:'روانشناسی سلامت', subtitle:'استاد عزیزی — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/Ravanshenasisalamatostadazizi', category:'روانشناسی', tags:['روانشناسی سلامت']},
{title:'روانشناسی سازمانی', subtitle:'استاد پرستو احمدی — چهارشنبه ۱۰ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BABBAAJGJ0GMDEWYHQTRJMQCCPFEISLH', category:'روانشناسی', tags:['روانشناسی سازمانی']},
{title:'روانشناسی سازمانی', subtitle:'استاد سعدی — یکشنبه ۱۲ تا ۱۴', platform:'whatsapp', url:'https://chat.whatsapp.com/D1vZRdssfcI2gzwKXiQ24g', category:'روانشناسی', tags:['روانشناسی سازمانی']},
{title:'روانشناسی سازمانی', subtitle:'استاد سعدی — دوشنبه ۱۴ تا ۱۶', platform:'whatsapp', url:'https://chat.whatsapp.com/HDpmt18PPiZ7ubmXVXWCMN', category:'روانشناسی', tags:['روانشناسی سازمانی']},
{title:'مشاوره تحصیلی و شغلی', subtitle:'استاد حسن‌زاده — پنجشنبه ۲ تا ۴', platform:'rubika', url:'https://rubika.ir/joing/BBHDCDEIA0ULWJYIVMWVXMRBPGJZEWLQ', category:'روانشناسی', tags:['مشاوره تحصیلی']},
{title:'راهنمایی مشاوره تحصیلی شغلی', subtitle:'استاد معلم زادگان', platform:'rubika', url:'https://rubika.ir/joing/BBGBBIJHC0MKYWGHVPZZVSYALXIWQETF', category:'روانشناسی', tags:['مشاوره تحصیلی']},
{title:'مبانی راهنمایی و مشاوره', subtitle:'استاد ملائی — تمامی ساعات', platform:'bale', url:'https://ble.ir/join/4X5HMBjqCo', category:'روانشناسی', tags:['مشاوره']},
{title:'فنون مشاوره', subtitle:'استاد محبی', platform:'rubika', url:'https://rubika.ir/joing/BBCIIEGGG0AANINRFUVZPRBRECWLBAHQ', category:'روانشناسی', tags:['فنون مشاوره']},
{title:'روانشناسی از دیدگاه اندیشمندان مسلمان', subtitle:'استاد محسن محمودی', platform:'bale', url:'https://ble.ir/join/6teKWbZtUy', category:'روانشناسی', tags:['اندیشمندان مسلمان']},
{title:'روانشناسی مشاوره خانواده', subtitle:'استاد ندا پگاه — تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBEHHBBJD0DLXOADNNDDNLQQAQWXGNZI', category:'روانشناسی', tags:['مشاوره خانواده']},
{title:'روانشناسی مشاوره خانواده', subtitle:'استاد ندا پگاه — واتساپ', platform:'whatsapp', url:'https://chat.whatsapp.com/FJcUk5A6oDF2UAsQHe5s6U', category:'روانشناسی', tags:['مشاوره خانواده']},
{title:'آزمون‌های روانشناختی ۱', subtitle:'استاد مجید عزیزی — تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBGEAGEAA0OIKQELMHQNUORYDZILZMCP', category:'روانشناسی', tags:['آزمون روانشناختی']},
{title:'روان‌سنجی', subtitle:'مرتضی رئیسی حسن لنگی', platform:'bale', url:'https://ble.ir/join/FCtiaogMFW', category:'روانشناسی', tags:['روان‌سنجی']},
{title:'مشاوره کودک', subtitle:'استاد اکرم درودی — چهارشنبه ۱۸ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BBHDEIJJE0GSHHBRGVAYVDLJDWUMFROL', category:'روانشناسی', tags:['مشاوره کودک']},
{title:'احساس و ادراک', subtitle:'استاد سپیده پنداشته — ۲ تا ۴', platform:'bale', url:'https://ble.ir/join/AZH33DtoSw', category:'روانشناسی', tags:['احساس و ادراک']},
{title:'کاربرد کامپیوتر در روانشناسی', subtitle:'استاد مانی مهین — تمام ساعات (بله)', platform:'bale', url:'https://ble.ir/join/CTEFTLeoPc', category:'روانشناسی', tags:['کاربرد کامپیوتر']},
{title:'کاربرد کامپیوتر در روانشناسی', subtitle:'استاد مانی مهین (روبیکا)', platform:'rubika', url:'https://rubika.ir/joing/BBEHGCJHE0KXZTUIFJUMNQXBJZZXKFND', category:'روانشناسی', tags:['کاربرد کامپیوتر']},
{title:'توانبخشی کودکان با نیازهای ویژه', subtitle:'استاد ملائی — تمام ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBEHIHBCJ0SGEAEBLCKGYVSGYTWGMERP', category:'روانشناسی', tags:['توانبخشی']},
{title:'ژورنال کلاب ۱', subtitle:'کارشناسی ارشد روانشناسی', platform:'eitaa', url:'https://eitaa.com/joinchat/695731777C715b3300eb', category:'روانشناسی', tags:['ژورنال کلاب']},
{title:'خانواده درمانی', subtitle:'کارشناسی ارشد روانشناسی', platform:'eitaa', url:'https://eitaa.com/joinchat/744818410C977b10e02d', category:'روانشناسی', tags:['خانواده درمانی']},
{title:'درمان‌های رفتاری، شناختی، هیجانی', subtitle:'کارشناسی ارشد', platform:'eitaa', url:'https://eitaa.com/joinchat/746981098Cd1b58df318', category:'روانشناسی', tags:['درمان شناختی']},
{title:'کارورزی درمان‌های رفتاری، شناختی، هیجانی', subtitle:'کارشناسی ارشد', platform:'eitaa', url:'https://eitaa.com/joinchat/748357354C3b06804121', category:'روانشناسی', tags:['کارورزی']},
{title:'گزارش موارد بالینی ۱', subtitle:'کارشناسی ارشد', platform:'eitaa', url:'https://eitaa.com/joinchat/4086892266Cbaab85dcdf', category:'روانشناسی', tags:['گزارش بالینی']},
{title:'مداخلات دینی و معنوی', subtitle:'کارشناسی ارشد', platform:'eitaa', url:'https://eitaa.com/joinchat/4187948778C7b6a723347', category:'روانشناسی', tags:['مداخلات دینی']},
{title:'کارورزی مداخلات دینی، معنوی', subtitle:'کارشناسی ارشد', platform:'eitaa', url:'https://eitaa.com/joinchat/4200859370Cbc7ebabca6', category:'روانشناسی', tags:['کارورزی']},
{title:'نوروسایکولوژی', subtitle:'کارشناسی ارشد', platform:'eitaa', url:'https://eitaa.com/joinchat/173803242C8cf6681646', category:'روانشناسی', tags:['نوروسایکولوژی']},
{title:'کارورزی آسیب‌شناسی روانی', subtitle:'کارشناسی ارشد', platform:'eitaa', url:'https://eitaa.com/joinchat/179177194C682bec7293', category:'روانشناسی', tags:['کارورزی']},
{title:'کلیات آسیب‌شناسی روانی', subtitle:'کارشناسی ارشد', platform:'eitaa', url:'https://eitaa.com/joinchat/157812458C3e9dde0093', category:'روانشناسی', tags:['آسیب‌شناسی']},
{title:'نظریه‌های معاصر شخصیت', subtitle:'کارشناسی ارشد', platform:'bale', url:'https://ble.ir/join/8936bZjqjf', category:'روانشناسی', tags:['نظریه شخصیت']},
{title:'اخلاق حرفه‌ای', subtitle:'کارشناسی ارشد', platform:'bale', url:'https://ble.ir/join/8pu97kWnkH', category:'روانشناسی', tags:['اخلاق حرفه‌ای']},
{title:'آمار پیشرفته بالینی', subtitle:'کارشناسی ارشد', platform:'bale', url:'https://ble.ir/join/6p9s9WKtEG', category:'روانشناسی', tags:['آمار پیشرفته']},

/* ═══════════════════════════════════════════════════════════
   📚 علوم تربیتی و آموزش ابتدایی
   ═══════════════════════════════════════════════════════════ */
{title:'سازمان و قوانین آموزش و پرورش', subtitle:'استاد ناهید سلطانی — یکشنبه ۱۸ تا ۲۰', platform:'rubika', url:'https://rubika.ir/joing/BBHBFECGC0LBEHGOJPFVRNOYJMZEMGMW', category:'علوم تربیتی', tags:['سازمان و قوانین']},
{title:'سیر تحول تعلیم و تربیت', subtitle:'استاد میترا فرهنگ — سه‌شنبه ۱۲ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BBHCGAEDH0WRSZNHDRHCLIRUQXDFJIKV', category:'علوم تربیتی', tags:['سیر تحول']},
{title:'سیر تحول تعلیم و تربیت در ایران', subtitle:'استاد اسکندری — یکشنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBHBEEIEG0LVEJXSULCDLSAKMNJOSPYE', category:'علوم تربیتی', tags:['سیر تحول']},
{title:'تکنولوژی آموزشی', subtitle:'سیما سلمانی — دوشنبه ۴ تا ۶', platform:'igap', url:'https://iGap.net/join/zHqUIBGtvjmbTVYHiZqianEgz', category:'علوم تربیتی', tags:['تکنولوژی آموزشی']},
{title:'کاربرد رایانه در تعلیم و تربیت', subtitle:'استاد جوادی‌زاده — چهارشنبه ۱۲ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BBHDCEAHG0MWFPCHMGTPDJSMYPGUDUFL', category:'علوم تربیتی', tags:['کاربرد رایانه']},
{title:'کاربرد رایانه در تعلیم و تربیت', subtitle:'ساعت ۱۴ تا ۱۶', platform:'rubika', url:'https://rubika.ir/joing/BBHDDDFJE0EQHTFTEXEZIOUBZWFOMCDC', category:'علوم تربیتی', tags:['کاربرد رایانه']},
{title:'آموزش و پرورش پیش‌دبستانی', subtitle:'استاد حسن‌زاده — چهارشنبه ۱۲ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BBHDCCDIH0FNOGPZDLDEBAMFQUFQRZIO', category:'علوم تربیتی', tags:['پیش‌دبستانی']},
{title:'اقتصاد تعلیم و تربیت', subtitle:'استاد فرخی سکل — چهارشنبه ۴ تا ۶', platform:'rubika', url:'https://rubika.ir/joing/BBHDEFFIJ0SWNZKUEEPZKPOMYVGGJNBW', category:'علوم تربیتی', tags:['اقتصاد تعلیم']},
{title:'مبانی و مدیریت اسلامی', subtitle:'علیرضا فرهنگ — چهارشنبه ۱۲ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BBHDCFDGA0SXTJWUXIZTEJPLDUHOQSIU', category:'علوم تربیتی', tags:['مدیریت اسلامی']},
{title:'تعلیم و تربیت اسلامی', subtitle:'استاد فرهنگ — چهارشنبه ۱۲ تا ۱۴', platform:'rubika', url:'https://rubika.ir/joing/BBHDCEGDF0OXDUHLFBYFKIAFNUUMRPLU', category:'علوم تربیتی', tags:['تعلیم و تربیت']},
{title:'اصول و مبانی مدیریت از دیدگاه اسلام', subtitle:'استاد فرجام خوارزمی', platform:'eitaa', url:'https://eitaa.com/joinchat/2589591307C305b598e70', category:'علوم تربیتی', tags:['مدیریت اسلامی']},
{title:'مکتب‌های فلسفی و نظریه‌های تربیتی', subtitle:'استاد فرهنگ — چهارشنبه ۱۰ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BBHDBJGHC0FKLALWCTIICAMIEMZLPWSE', category:'علوم تربیتی', tags:['مکتب فلسفی']},
{title:'مکتب‌های فلسفی و نظریه‌های تربیتی', subtitle:'استاد دریوش', platform:'rubika', url:'https://rubika.ir/joing/BBGHCICIA0ADMDSTZXNALTSHPLEPMGIX', category:'علوم تربیتی', tags:['مکتب فلسفی']},
{title:'آموزه‌های تربیتی', subtitle:'استاد علیرضا فرهنگ — ۱۰ تا ۱۲', platform:'rubika', url:'https://rubika.ir/joing/BBGJHEEHA0SRAPYTUXACDYZOOYEYDXBS', category:'علوم تربیتی', tags:['آموزه تربیتی']},
{title:'نظارت و راهنمایی آموزشی', subtitle:'علی ابراهیمی قلعه‌قاضی — ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBDAJAJDJ0NOXARDYNLFCJKTHZPXXHZP', category:'علوم تربیتی', tags:['نظارت آموزشی','تابستان']},
{title:'مبانی و اصول مدیریت آموزشی', subtitle:'استاد علی ابراهیمی — یکشنبه ۲ تا ۴', platform:'whatsapp', url:'https://chat.whatsapp.com/GZD6ZMpEnkK2mYmpbj8SB4', category:'علوم تربیتی', tags:['مدیریت آموزشی']},
{title:'مبانی امور مالی و تنظیم بودجه در آموزش و پرورش', subtitle:'میلاد فرخی — شنبه ۱۶ تا ۱۸', platform:'rubika', url:'https://rubika.ir/joing/BBHAIECAF0ZBKHTFTCUDRBCCGBRDMYSU', category:'علوم تربیتی', tags:['بودجه آموزش']},
{title:'مبانی امور مالی و تنظیم بودجه', subtitle:'استاد شفیع‌زاده — ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBDGDFIDG0CYMOASWBAZTVTFDFMTENHA', category:'علوم تربیتی', tags:['بودجه آموزش','تابستان']},
{title:'تدوین و نگارش متون', subtitle:'استاد علیمرادی — یکشنبه ۸ تا ۱۰', platform:'rubika', url:'https://rubika.ir/joing/BBHBCCIBF0BLMKUSGAUUPMYTWYIVTUSH', category:'علوم تربیتی', tags:['تدوین متون']},
{title:'تدوین نگارش متون و گزارش عملی', subtitle:'مریم علیمرادی — یکشنبه ۸ تا ۱۰', platform:'rubika', url:'https://rubika.ir/joing/BBHBCCIBF0BLMKUSGAUUPMYTWYIVTUSH', category:'علوم تربیتی', tags:['تدوین متون']},
{title:'اخلاق حرفه‌ای در تعلیم و تربیت', subtitle:'استاد نازیلا عامری سیاهویی — شنبه ۱۳ تا ۱۵', platform:'rubika', url:'https://rubika.ir/joing/BBHAHCCBG0NTDHLOPWCOKDKYZSMSBBJJ', category:'علوم تربیتی', tags:['اخلاق حرفه‌ای']},
{title:'ارزشیابی آموزشی', subtitle:'استاد سالاری — ترم تابستان', platform:'rubika', url:'https://rubika.ir/joing/BBDAHGFGE0HYUOQIGKWIFDVLNLVOULLT', category:'علوم تربیتی', tags:['ارزشیابی','تابستان']},
{title:'تحلیل محتوای کتاب‌های درسی ۱ و ارزشیابی پیشرفت تحصیلی', subtitle:'استاد مهین غلام‌زاده میناب', platform:'eitaa', url:'https://eitaa.com/joinchat/1391920893Cd4deff7cbf', category:'علوم تربیتی', tags:['تحلیل محتوا']},
{title:'سنجش و اندازه‌گیری', subtitle:'استاد اسکندری — یکشنبه ۱۴ تا ۱۶', platform:'rubika', url:'https://rubika.ir/joing/BBGHCGBIB0TWWHDNEAZBBVJWVNCZPAFS', category:'علوم تربیتی', tags:['سنجش']},
{title:'تحلیل محتوای کتاب‌های درسی ۱', subtitle:'همه ساعات — فقط ترم ۲', platform:'rubika', url:'https://rubika.ir/joing/BBHDEBCFA0OVFEFQTWPIMFBWWFGNOZXS', category:'علوم تربیتی', tags:['تحلیل محتوا']},
{title:'مبانی برنامه‌ریزی درسی', subtitle:'همه ساعات', platform:'rubika', url:'https://rubika.ir/joing/BBHDEBFGG0JBRXVOSDCFKVEVGUBTLMHS', category:'علوم تربیتی', tags:['برنامه‌ریزی']},
{title:'طراحی آموزشی', subtitle:'استاد سمیه زارع — پنجشنبه ۱۶ تا ۱۸', platform:'bale', url:'https://ble.ir/tarahiamozeshi2', category:'علوم تربیتی', tags:['طراحی آموزشی']},
{title:'آموزش مطالعات اجتماعی دوره ابتدایی', subtitle:'استاد عصام طاهری', platform:'whatsapp', url:'https://chat.whatsapp.com/KJmFIlzumzFLIY3RN87wrb', category:'علوم تربیتی', tags:['مطالعات اجتماعی']},
{title:'متون تخصصی', subtitle:'استاد زاهدیان — سه‌شنبه ۸ تا ۱۰', platform:'rubika', url:'https://rubika.ir/joing/BBGHIGGGF0VYHMGXTFBWTVVMLSVYQNXV', category:'علوم تربیتی', tags:['متون تخصصی']},
{title:'متون تخصصی علوم تربیتی', subtitle:'استاد سالاری — سه‌شنبه', platform:'rubika', url:'https://rubika.ir/joing/BBDCBHFID0TQGFKSPDQRONKJVYYFADPF', category:'علوم تربیتی', tags:['متون تخصصی']},
{title:'گروه اطلاع‌رسانی کلاس‌ها', subtitle:'استاد مهرناز احمدغلامی — آموزش ابتدایی', platform:'rubika', url:'https://rubika.ir/joing/BBGIJDBHI0OXCEDLOWWJKKJTUDFFOSCE', category:'علوم تربیتی', tags:['اطلاع‌رسانی']},
{title:'پژوهش عملی انفرادی', subtitle:'استاد بتول ملائی', platform:'bale', url:'https://ble.ir/join/7Ad1femgNj', category:'علوم تربیتی', tags:['پژوهش']},

/* ═══════════════════════════════════════════════════════════
   🎓 گروه‌های عمومی دانشگاه
   ═══════════════════════════════════════════════════════════ */
{title:'گروه تلگرام دانشگاه آزاد بندرعباس', subtitle:'گفتگوی عمومی دانشجویان', platform:'telegram', url:'https://t.me/daneshgah_azad0', category:'گروه‌های عمومی', tags:['گفتگو']},
{title:'گروه واتساپ دانشگاه', subtitle:'گفتگوی عمومی', platform:'whatsapp', url:'https://chat.whatsapp.com/LmRuoZDyXOf7oV5sTeDrmc', category:'گروه‌های عمومی', tags:['گفتگو']},
{title:'گفتگو دانشجویی روبیکا', subtitle:'گروه گفتگوی دانشجویان', platform:'rubika', url:'https://rubika.ir/joing/JJEJJIDE0XSLWUJEKTAQESLMRDHEFNGW', category:'گروه‌های عمومی', tags:['گفتگو']},
{title:'گفتگو دانشگاه آزاد روبیکا', subtitle:'گروه گفتگوی عمومی', platform:'rubika', url:'https://rubika.ir/joing/JJEJJDFB0FJRTOGBNFHZAXROYRPNIGHV', category:'گروه‌های عمومی', tags:['گفتگو']},
{title:'کانال سروش', subtitle:'Daneshdj', platform:'soroush', url:'https://splus.ir/Daneshdj', category:'گروه‌های عمومی', tags:['کانال']},
{title:'خرید و فروش کتاب', subtitle:'گروه دانشجویی', platform:'rubika', url:'https://rubika.ir/joing/BADDDFJAB0ACVFNZLRCNIPSDILCRDNVU', category:'گروه‌های عمومی', tags:['کتاب']},
{title:'تبلیغات کسب‌وکار دانشجویی', subtitle:'گروه دانشجویی', platform:'rubika', url:'https://rubika.ir/joing/BAGBDGIAD0TYCEGTGEQNCVLDANQPOLCN', category:'گروه‌های عمومی', tags:['تبلیغات']},
{title:'کانال صفدری نیاک', subtitle:'دکتر صفدری نیاک — روبیکا', platform:'rubika', url:'https://rubika.ir/murtezasafdariniak', category:'گروه‌های عمومی', tags:['کانال']},
];

/* ============================================================
   دسته‌بندی‌ها برای نمایش در چیپ‌ها
   ============================================================ */
const CATEGORIES = [
  'همه',
  'عمومی',
  'زبان',
  'حسابداری',
  'حقوق',
  'مدیریت',
  'کامپیوتر',
  'روانشناسی',
  'علوم تربیتی',
  'گروه‌های عمومی',
];